"""
College-name -> (city, state) crosswalk, keyed by the register's normalized
school name: str(school).strip().lower().

This built-in table covers the major baseball-producing programs (the head of
the distribution that accounts for most college draftees). Names are the
INFORMAL forms as they appear in the The Baseball Cube register (e.g. 'miami',
'cal state fullerton', 'long beach state'), NOT official IPEDS names.

Locations are campus city/state -- the point we measure birth->college distance
to. For multi-campus or ambiguous names, the baseball-program campus is used
(e.g. 'miami' = University of Miami, Coral Gables FL, the baseball school --
NOT Miami University Ohio).

Coverage is intentionally the high-value head. The resolver (resolve_colleges.py)
reports unmatched schools ranked by draftee count so the tail can be filled.

Add entries as: 'normalized name': ('City', 'ST'),
"""

CROSSWALK = {
    # --- top baseball programs by draftee volume ---
    'miami': ('Coral Gables', 'FL'),          # U Miami (baseball school)
    'arizona state': ('Tempe', 'AZ'),
    'cal state fullerton': ('Fullerton', 'CA'),
    'stanford': ('Stanford', 'CA'),
    'texas': ('Austin', 'TX'),
    'rice': ('Houston', 'TX'),
    'ucla': ('Los Angeles', 'CA'),
    'texas a&m': ('College Station', 'TX'),
    'lsu': ('Baton Rouge', 'LA'),
    'florida': ('Gainesville', 'FL'),
    'oklahoma': ('Norman', 'OK'),
    'clemson': ('Clemson', 'SC'),
    'oklahoma state': ('Stillwater', 'OK'),
    'south carolina': ('Columbia', 'SC'),
    'long beach state': ('Long Beach', 'CA'),
    'florida state': ('Tallahassee', 'FL'),
    'georgia tech': ('Atlanta', 'GA'),
    'arkansas': ('Fayetteville', 'AR'),
    'vanderbilt': ('Nashville', 'TN'),
    'mississippi state': ('Starkville', 'MS'),
    'north carolina': ('Chapel Hill', 'NC'),
    'cal': ('Berkeley', 'CA'),
    'california': ('Berkeley', 'CA'),
    'southern california': ('Los Angeles', 'CA'),
    'usc': ('Los Angeles', 'CA'),
    'auburn': ('Auburn', 'AL'),
    'alabama': ('Tuscaloosa', 'AL'),
    'georgia': ('Athens', 'GA'),
    'tennessee': ('Knoxville', 'TN'),
    'ole miss': ('Oxford', 'MS'),
    'mississippi': ('Oxford', 'MS'),
    'wichita state': ('Wichita', 'KS'),
    'oregon state': ('Corvallis', 'OR'),
    'oregon': ('Eugene', 'OR'),
    'baylor': ('Waco', 'TX'),
    'texas tech': ('Lubbock', 'TX'),
    'tcu': ('Fort Worth', 'TX'),
    'houston': ('Houston', 'TX'),
    'san diego state': ('San Diego', 'CA'),
    'san diego': ('San Diego', 'CA'),
    'uc irvine': ('Irvine', 'CA'),
    'uc santa barbara': ('Santa Barbara', 'CA'),
    'uc davis': ('Davis', 'CA'),
    'uc riverside': ('Riverside', 'CA'),
    'pepperdine': ('Malibu', 'CA'),
    'loyola marymount': ('Los Angeles', 'CA'),
    'santa clara': ('Santa Clara', 'CA'),
    'fresno state': ('Fresno', 'CA'),
    'san jose state': ('San Jose', 'CA'),
    'sacramento state': ('Sacramento', 'CA'),
    'nevada': ('Reno', 'NV'),
    'unlv': ('Las Vegas', 'NV'),
    'arizona': ('Tucson', 'AZ'),
    'new mexico': ('Albuquerque', 'NM'),
    'washington': ('Seattle', 'WA'),
    'washington state': ('Pullman', 'WA'),
    'gonzaga': ('Spokane', 'WA'),
    'portland': ('Portland', 'OR'),
    'notre dame': ('Notre Dame', 'IN'),
    'michigan': ('Ann Arbor', 'MI'),
    'michigan state': ('East Lansing', 'MI'),
    'ohio state': ('Columbus', 'OH'),
    'indiana': ('Bloomington', 'IN'),
    'illinois': ('Champaign', 'IL'),
    'purdue': ('West Lafayette', 'IN'),
    'minnesota': ('Minneapolis', 'MN'),
    'iowa': ('Iowa City', 'IA'),
    'nebraska': ('Lincoln', 'NE'),
    'kansas': ('Lawrence', 'KS'),
    'kansas state': ('Manhattan', 'KS'),
    'missouri': ('Columbia', 'MO'),
    'wisconsin': ('Madison', 'WI'),
    'northwestern': ('Evanston', 'IL'),
    'penn state': ('University Park', 'PA'),
    'maryland': ('College Park', 'MD'),
    'virginia': ('Charlottesville', 'VA'),
    'virginia tech': ('Blacksburg', 'VA'),
    'nc state': ('Raleigh', 'NC'),
    'north carolina state': ('Raleigh', 'NC'),
    'wake forest': ('Winston-Salem', 'NC'),
    'duke': ('Durham', 'NC'),
    'east carolina': ('Greenville', 'NC'),
    'coastal carolina': ('Conway', 'SC'),
    'georgia southern': ('Statesboro', 'GA'),
    'kentucky': ('Lexington', 'KY'),
    'louisville': ('Louisville', 'KY'),
    'cincinnati': ('Cincinnati', 'OH'),
    'connecticut': ('Storrs', 'CT'),
    'uconn': ('Storrs', 'CT'),
    'boston college': ('Chestnut Hill', 'MA'),
    'florida international': ('Miami', 'FL'),
    'central florida': ('Orlando', 'FL'),
    'ucf': ('Orlando', 'FL'),
    'south florida': ('Tampa', 'FL'),
    'stetson': ('DeLand', 'FL'),
    'jacksonville': ('Jacksonville', 'FL'),
    'miami (ohio)': ('Oxford', 'OH'),
    'tulane': ('New Orleans', 'LA'),
    'louisiana': ('Lafayette', 'LA'),
    'louisiana state': ('Baton Rouge', 'LA'),
    'louisiana tech': ('Ruston', 'LA'),
    'southern miss': ('Hattiesburg', 'MS'),
    'southern mississippi': ('Hattiesburg', 'MS'),
    'dallas baptist': ('Dallas', 'TX'),
    'sam houston state': ('Huntsville', 'TX'),
    'texas state': ('San Marcos', 'TX'),
    'ut arlington': ('Arlington', 'TX'),
    'uc san diego': ('La Jolla', 'CA'),
    'cal poly': ('San Luis Obispo', 'CA'),
    'cal state northridge': ('Northridge', 'CA'),
    'cal state long beach': ('Long Beach', 'CA'),
    'cal state los angeles': ('Los Angeles', 'CA'),
    'cal state sacramento': ('Sacramento', 'CA'),
    'saint marys': ("Moraga", 'CA'),
    "saint mary's": ('Moraga', 'CA'),
    'st. marys': ('Moraga', 'CA'),
    'grand canyon': ('Phoenix', 'AZ'),
    'byu': ('Provo', 'UT'),
    'utah': ('Salt Lake City', 'UT'),
    'brigham young': ('Provo', 'UT'),

    # --- second tranche: recognizable 4-year + big JUCOs from the punch-list ---
    'texas christian': ('Fort Worth', 'TX'),
    'san jacinto': ('Pasadena', 'TX'),          # San Jacinto College, JUCO
    'chipola': ('Marianna', 'FL'),              # Chipola College, JUCO
    'miami dade': ('Miami', 'FL'),
    'miami-dade': ('Miami', 'FL'),
    'florida atlantic': ('Boca Raton', 'FL'),
    'tampa': ('Tampa', 'FL'),
    'missouri state': ('Springfield', 'MO'),
    'florida intl': ('Miami', 'FL'),
    'oral roberts': ('Tulsa', 'OK'),
    "st. john's": ('Queens', 'NY'),
    "st. johns": ('Queens', 'NY'),
    'kent state': ('Kent', 'OH'),
    'lewis-clark idaho': ('Lewiston', 'ID'),    # Lewis-Clark State, NAIA power
    'lewis-clark state': ('Lewiston', 'ID'),
    'central arizona college': ('Coolidge', 'AZ'),
    'central arizona': ('Coolidge', 'AZ'),
    'south alabama': ('Mobile', 'AL'),
    'west virginia': ('Morgantown', 'WV'),
    'louisiana-lafayette': ('Lafayette', 'LA'),
    'st. petersburg college': ('St. Petersburg', 'FL'),
    'southern nevada': ('Henderson', 'NV'),     # CSN, JUCO
    'riverside cc': ('Riverside', 'CA'),
    'riverside community college': ('Riverside', 'CA'),
    'unc wilmington': ('Wilmington', 'NC'),
    'lamar': ('Beaumont', 'TX'),
    'college of charleston': ('Charleston', 'SC'),
    'cypress college': ('Cypress', 'CA'),
    'cowley college': ('Arkansas City', 'KS'),
    'cowley county cc': ('Arkansas City', 'KS'),
    'liberty': ('Lynchburg', 'VA'),
    # more common 4-year programs
    'old dominion': ('Norfolk', 'VA'),
    'james madison': ('Harrisonburg', 'VA'),
    'george mason': ('Fairfax', 'VA'),
    'richmond': ('Richmond', 'VA'),
    'william & mary': ('Williamsburg', 'VA'),
    'vcu': ('Richmond', 'VA'),
    'davidson': ('Davidson', 'NC'),
    'elon': ('Elon', 'NC'),
    'appalachian state': ('Boone', 'NC'),
    'western carolina': ('Cullowhee', 'NC'),
    'charlotte': ('Charlotte', 'NC'),
    'unc charlotte': ('Charlotte', 'NC'),
    'unc greensboro': ('Greensboro', 'NC'),
    'furman': ('Greenville', 'SC'),
    'the citadel': ('Charleston', 'SC'),
    'winthrop': ('Rock Hill', 'SC'),
    'wofford': ('Spartanburg', 'SC'),
    'mercer': ('Macon', 'GA'),
    'kennesaw state': ('Kennesaw', 'GA'),
    'georgia state': ('Atlanta', 'GA'),
    'jacksonville state': ('Jacksonville', 'AL'),
    'troy': ('Troy', 'AL'),
    'samford': ('Birmingham', 'AL'),
    'uab': ('Birmingham', 'AL'),
    'south florida': ('Tampa', 'FL'),
    'bethune-cookman': ('Daytona Beach', 'FL'),
    'florida gulf coast': ('Fort Myers', 'FL'),
    'north florida': ('Jacksonville', 'FL'),
    'florida southern': ('Lakeland', 'FL'),
    'nova southeastern': ('Fort Lauderdale', 'FL'),
    'embry-riddle': ('Daytona Beach', 'FL'),
    'polk state': ('Winter Haven', 'FL'),
    'santa fe college': ('Gainesville', 'FL'),
    'seminole state': ('Sanford', 'FL'),
    'indian river state': ('Fort Pierce', 'FL'),
    'hillsborough cc': ('Tampa', 'FL'),
    'pensacola state': ('Pensacola', 'FL'),
    'northwest florida state': ('Niceville', 'FL'),
    'gulf coast state': ('Panama City', 'FL'),
    'manatee cc': ('Bradenton', 'FL'),
    'state college of florida': ('Bradenton', 'FL'),
    'wabash valley': ('Mount Carmel', 'IL'),
    'john a. logan': ('Carterville', 'IL'),
    'southeastern illinois': ('Harrisburg', 'IL'),
    'lincoln land': ('Springfield', 'IL'),
    'kaskaskia': ('Centralia', 'IL'),
    'illinois central': ('East Peoria', 'IL'),
    'parkland college': ('Champaign', 'IL'),
    'triton college': ('River Grove', 'IL'),
    'southern illinois': ('Carbondale', 'IL'),
    'illinois state': ('Normal', 'IL'),
    'bradley': ('Peoria', 'IL'),
    'creighton': ('Omaha', 'NE'),
    'wichita state': ('Wichita', 'KS'),
    'cowley': ('Arkansas City', 'KS'),
    'butler cc': ('El Dorado', 'KS'),
    'seward county cc': ('Liberal', 'KS'),
    'hutchinson cc': ('Hutchinson', 'KS'),
    'johnson county cc': ('Overland Park', 'KS'),
    'neosho county cc': ('Chanute', 'KS'),
    'coffeyville cc': ('Coffeyville', 'KS'),
    'labette cc': ('Parsons', 'KS'),
    'barton county cc': ('Great Bend', 'KS'),
    'dodge city cc': ('Dodge City', 'KS'),
    'garden city cc': ('Garden City', 'KS'),
    'wichita state university': ('Wichita', 'KS'),
    'san jacinto college': ('Pasadena', 'TX'),
    'blinn college': ('Brenham', 'TX'),
    'blinn': ('Brenham', 'TX'),
    'navarro college': ('Corsicana', 'TX'),
    'navarro': ('Corsicana', 'TX'),
    'mclennan cc': ('Waco', 'TX'),
    'mclennan': ('Waco', 'TX'),
    'weatherford college': ('Weatherford', 'TX'),
    'grayson college': ('Denison', 'TX'),
    'grayson county college': ('Denison', 'TX'),
    'temple college': ('Temple', 'TX'),
    'galveston college': ('Galveston', 'TX'),
    'alvin cc': ('Alvin', 'TX'),
    'wharton county junior college': ('Wharton', 'TX'),
    'paris junior college': ('Paris', 'TX'),
    'angelina college': ('Lufkin', 'TX'),
    'panola college': ('Carthage', 'TX'),
    'texarkana college': ('Texarkana', 'TX'),
    'howard college': ('Big Spring', 'TX'),
    'midland college': ('Midland', 'TX'),
    'odessa college': ('Odessa', 'TX'),
    'south plains college': ('Levelland', 'TX'),
    'western texas college': ('Snyder', 'TX'),
    'new mexico junior college': ('Hobbs', 'NM'),
    'new mexico jc': ('Hobbs', 'NM'),
    'stephen f. austin': ('Nacogdoches', 'TX'),
    'stephen f austin': ('Nacogdoches', 'TX'),
    'texas-arlington': ('Arlington', 'TX'),
    'texas-san antonio': ('San Antonio', 'TX'),
    'utsa': ('San Antonio', 'TX'),
    'texas-pan american': ('Edinburg', 'TX'),
    'texas southern': ('Houston', 'TX'),
    'prairie view a&m': ('Prairie View', 'TX'),
    'incarnate word': ('San Antonio', 'TX'),
    'abilene christian': ('Abilene', 'TX'),
    'tarleton state': ('Stephenville', 'TX'),
    'angelo state': ('San Angelo', 'TX'),
    'west texas a&m': ('Canyon', 'TX'),
    'texas a&m-corpus christi': ('Corpus Christi', 'TX'),
    'texas a&m-kingsville': ('Kingsville', 'TX'),
    'houston baptist': ('Houston', 'TX'),
    'san jacinto north': ('Houston', 'TX'),
    'arizona western': ('Yuma', 'AZ'),
    'arizona western college': ('Yuma', 'AZ'),
    'yavapai college': ('Prescott', 'AZ'),
    'yavapai': ('Prescott', 'AZ'),
    'mesa cc': ('Mesa', 'AZ'),
    'scottsdale cc': ('Scottsdale', 'AZ'),
    'chandler-gilbert cc': ('Chandler', 'AZ'),
    'pima cc': ('Tucson', 'AZ'),
    'phoenix college': ('Phoenix', 'AZ'),
    'glendale cc': ('Glendale', 'AZ'),
    'south mountain cc': ('Phoenix', 'AZ'),
    'paradise valley cc': ('Phoenix', 'AZ'),
    'gateway cc': ('Phoenix', 'AZ'),
    'eastern arizona': ('Thatcher', 'AZ'),
    'cochise college': ('Douglas', 'AZ'),
    'grand canyon university': ('Phoenix', 'AZ'),
    'orange coast college': ('Costa Mesa', 'CA'),
    'orange coast': ('Costa Mesa', 'CA'),
    'golden west college': ('Huntington Beach', 'CA'),
    'santa ana college': ('Santa Ana', 'CA'),
    'santa ana': ('Santa Ana', 'CA'),
    'fullerton college': ('Fullerton', 'CA'),
    'saddleback college': ('Mission Viejo', 'CA'),
    'cypress': ('Cypress', 'CA'),
    'mt. san antonio': ('Walnut', 'CA'),
    'mt. san antonio college': ('Walnut', 'CA'),
    'mt. san jacinto': ('San Jacinto', 'CA'),
    'riverside city college': ('Riverside', 'CA'),
    'san bernardino valley': ('San Bernardino', 'CA'),
    'chaffey college': ('Rancho Cucamonga', 'CA'),
    'palomar college': ('San Marcos', 'CA'),
    'palomar': ('San Marcos', 'CA'),
    'grossmont college': ('El Cajon', 'CA'),
    'san diego city college': ('San Diego', 'CA'),
    'san diego mesa': ('San Diego', 'CA'),
    'southwestern college': ('Chula Vista', 'CA'),
    'long beach city college': ('Long Beach', 'CA'),
    'el camino college': ('Torrance', 'CA'),
    'los angeles harbor': ('Wilmington', 'CA'),
    'los angeles pierce': ('Woodland Hills', 'CA'),
    'glendale cc (ca)': ('Glendale', 'CA'),
    'pasadena city college': ('Pasadena', 'CA'),
    'citrus college': ('Glendora', 'CA'),
    'mt. sac': ('Walnut', 'CA'),
    'santa monica college': ('Santa Monica', 'CA'),
    'ventura college': ('Ventura', 'CA'),
    'moorpark college': ('Moorpark', 'CA'),
    'santa barbara city college': ('Santa Barbara', 'CA'),
    'bakersfield college': ('Bakersfield', 'CA'),
    'college of the canyons': ('Santa Clarita', 'CA'),
    'antelope valley college': ('Lancaster', 'CA'),
    'fresno city college': ('Fresno', 'CA'),
    'college of the sequoias': ('Visalia', 'CA'),
    'san joaquin delta': ('Stockton', 'CA'),
    'sacramento city college': ('Sacramento', 'CA'),
    'american river college': ('Sacramento', 'CA'),
    'sierra college': ('Rocklin', 'CA'),
    'santa rosa junior college': ('Santa Rosa', 'CA'),
    'college of san mateo': ('San Mateo', 'CA'),
    'chabot college': ('Hayward', 'CA'),
    'diablo valley college': ('Pleasant Hill', 'CA'),
    'san francisco city college': ('San Francisco', 'CA'),
    'cosumnes river': ('Sacramento', 'CA'),
    'san diego state university': ('San Diego', 'CA'),
    'cal state san bernardino': ('San Bernardino', 'CA'),
    'cal state dominguez hills': ('Carson', 'CA'),
    'cal state bakersfield': ('Bakersfield', 'CA'),
    'cal state stanislaus': ('Turlock', 'CA'),
    'cal state east bay': ('Hayward', 'CA'),
    'cal state monterey bay': ('Seaside', 'CA'),
    'sonoma state': ('Rohnert Park', 'CA'),
    'humboldt state': ('Arcata', 'CA'),
    'point loma nazarene': ('San Diego', 'CA'),
    'azusa pacific': ('Azusa', 'CA'),
    'biola': ('La Mirada', 'CA'),
    'concordia (ca)': ('Irvine', 'CA'),
    'redlands': ('Redlands', 'CA'),
    'chapman': ('Orange', 'CA'),
    'la verne': ('La Verne', 'CA'),
    'occidental': ('Los Angeles', 'CA'),
    'pomona-pitzer': ('Claremont', 'CA'),
    'menlo college': ('Atherton', 'CA'),

    # --- third tranche: matched to the register's EXACT spellings ---
    'st col of fl': ('Bradenton', 'FL'),
    'hawaii': ('Honolulu', 'HI'),
    'san francisco': ('San Francisco', 'CA'),   # University of San Francisco
    'ball state': ('Muncie', 'IN'),
    'grayson county': ('Denison', 'TX'),
    'sacramento city': ('Sacramento', 'CA'),
    'oklahoma city': ('Oklahoma City', 'OK'),
    'indian river cc': ('Fort Pierce', 'FL'),
    'pittsburgh': ('Pittsburgh', 'PA'),
    "st. mary's (ca)": ('Moraga', 'CA'),
    'csun': ('Northridge', 'CA'),
    'nw florida state': ('Niceville', 'FL'),
    'walters state cc': ('Morristown', 'TN'),
    'seton hall': ('South Orange', 'NJ'),
    'middle tenn state': ('Murfreesboro', 'TN'),
    'memphis': ('Memphis', 'TN'),
    'indiana state': ('Terre Haute', 'IN'),
    'palm beach state': ('Lake Worth', 'FL'),
    'connors state college': ('Warner', 'OK'),
    'pacific': ('Stockton', 'CA'),
    'meridian cc': ('Meridian', 'MS'),
    'rutgers': ('Piscataway', 'NJ'),
    'seminole ok': ('Seminole', 'OK'),
    'seminole florida': ('Sanford', 'FL'),
    'gulf coast cc': ('Panama City', 'FL'),
    # continue with common programs likely in the tail
    'wright state': ('Dayton', 'OH'),
    'ohio': ('Athens', 'OH'),
    'toledo': ('Toledo', 'OH'),
    'akron': ('Akron', 'OH'),
    'bowling green': ('Bowling Green', 'OH'),
    'miami ohio': ('Oxford', 'OH'),
    'xavier': ('Cincinnati', 'OH'),
    'dayton': ('Dayton', 'OH'),
    'youngstown state': ('Youngstown', 'OH'),
    'central michigan': ('Mount Pleasant', 'MI'),
    'western michigan': ('Kalamazoo', 'MI'),
    'eastern michigan': ('Ypsilanti', 'MI'),
    'oakland': ('Rochester', 'MI'),
    'northern illinois': ('DeKalb', 'IL'),
    'western illinois': ('Macomb', 'IL'),
    'eastern illinois': ('Charleston', 'IL'),
    'chicago state': ('Chicago', 'IL'),
    'valparaiso': ('Valparaiso', 'IN'),
    'butler': ('Indianapolis', 'IN'),
    'evansville': ('Evansville', 'IN'),
    'indiana-purdue': ('Indianapolis', 'IN'),
    'ball state university': ('Muncie', 'IN'),
    'ohio state university': ('Columbus', 'OH'),
    'west virginia university': ('Morgantown', 'WV'),
    'marshall': ('Huntington', 'WV'),
    'pittsburgh university': ('Pittsburgh', 'PA'),
    'penn': ('Philadelphia', 'PA'),
    'pennsylvania': ('Philadelphia', 'PA'),
    'villanova': ('Villanova', 'PA'),
    'temple': ('Philadelphia', 'PA'),
    'la salle': ('Philadelphia', 'PA'),
    'saint josephs': ('Philadelphia', 'PA'),
    "saint joseph's": ('Philadelphia', 'PA'),
    'drexel': ('Philadelphia', 'PA'),
    'lafayette': ('Easton', 'PA'),
    'lehigh': ('Bethlehem', 'PA'),
    'bucknell': ('Lewisburg', 'PA'),
    'duquesne': ('Pittsburgh', 'PA'),
    'robert morris': ('Moon', 'PA'),
    'rider': ('Lawrenceville', 'NJ'),
    'monmouth': ('West Long Branch', 'NJ'),
    'princeton': ('Princeton', 'NJ'),
    'njit': ('Newark', 'NJ'),
    'fairleigh dickinson': ('Teaneck', 'NJ'),
    'wagner': ('Staten Island', 'NY'),
    'fordham': ('Bronx', 'NY'),
    'manhattan': ('Riverdale', 'NY'),
    'iona': ('New Rochelle', 'NY'),
    'siena': ('Loudonville', 'NY'),
    'canisius': ('Buffalo', 'NY'),
    'niagara': ('Lewiston', 'NY'),
    'stony brook': ('Stony Brook', 'NY'),
    'binghamton': ('Binghamton', 'NY'),
    'albany': ('Albany', 'NY'),
    'buffalo': ('Buffalo', 'NY'),
    'columbia': ('New York', 'NY'),
    'cornell': ('Ithaca', 'NY'),
    'army': ('West Point', 'NY'),
    'navy': ('Annapolis', 'MD'),
    'air force': ('Colorado Springs', 'CO'),
    'hofstra': ('Hempstead', 'NY'),
    'st. bonaventure': ('St. Bonaventure', 'NY'),
    'marist': ('Poughkeepsie', 'NY'),
    'quinnipiac': ('Hamden', 'CT'),
    'sacred heart': ('Fairfield', 'CT'),
    'central connecticut': ('New Britain', 'CT'),
    'yale': ('New Haven', 'CT'),
    'hartford': ('West Hartford', 'CT'),
    'fairfield': ('Fairfield', 'CT'),
    'bryant': ('Smithfield', 'RI'),
    'providence': ('Providence', 'RI'),
    'brown': ('Providence', 'RI'),
    'rhode island': ('Kingston', 'RI'),
    'harvard': ('Cambridge', 'MA'),
    'northeastern': ('Boston', 'MA'),
    'boston university': ('Boston', 'MA'),
    'umass': ('Amherst', 'MA'),
    'massachusetts': ('Amherst', 'MA'),
    'umass lowell': ('Lowell', 'MA'),
    'holy cross': ('Worcester', 'MA'),
    'maine': ('Orono', 'ME'),
    'vermont': ('Burlington', 'VT'),
    'new hampshire': ('Durham', 'NH'),
    'dartmouth': ('Hanover', 'NH'),
    'delaware': ('Newark', 'DE'),
    'towson': ('Towson', 'MD'),
    'umbc': ('Baltimore', 'MD'),
    'coppin state': ('Baltimore', 'MD'),
    'mount st. marys': ('Emmitsburg', 'MD'),
    'george washington': ('Washington', 'DC'),
    'georgetown': ('Washington', 'DC'),
    'american': ('Washington', 'DC'),
    'howard': ('Washington', 'DC'),
    'radford': ('Radford', 'VA'),
    'longwood': ('Farmville', 'VA'),
    'liberty university': ('Lynchburg', 'VA'),
    'norfolk state': ('Norfolk', 'VA'),
    'hampton': ('Hampton', 'VA'),
    'high point': ('High Point', 'NC'),
    'gardner-webb': ('Boiling Springs', 'NC'),
    'campbell': ('Buies Creek', 'NC'),
    'unc asheville': ('Asheville', 'NC'),
    'unc greensboro': ('Greensboro', 'NC'),
    'presbyterian': ('Clinton', 'SC'),
    'south carolina state': ('Orangeburg', 'SC'),
    'coastal carolina university': ('Conway', 'SC'),
    'usc upstate': ('Spartanburg', 'SC'),
    'usc aiken': ('Aiken', 'SC'),
    'georgia college': ('Milledgeville', 'GA'),
    'valdosta state': ('Valdosta', 'GA'),
    'columbus state': ('Columbus', 'GA'),
    'west georgia': ('Carrollton', 'GA'),
    'north georgia': ('Dahlonega', 'GA'),
    'augusta': ('Augusta', 'GA'),
    'savannah state': ('Savannah', 'GA'),
    'florida a&m': ('Tallahassee', 'FL'),
    'stetson university': ('DeLand', 'FL'),
    'lipscomb': ('Nashville', 'TN'),
    'belmont': ('Nashville', 'TN'),
    'tennessee tech': ('Cookeville', 'TN'),
    'tennessee-martin': ('Martin', 'TN'),
    'austin peay': ('Clarksville', 'TN'),
    'east tennessee state': ('Johnson City', 'TN'),
    'chattanooga': ('Chattanooga', 'TN'),
    'vanderbilt university': ('Nashville', 'TN'),
    'western kentucky': ('Bowling Green', 'KY'),
    'eastern kentucky': ('Richmond', 'KY'),
    'morehead state': ('Morehead', 'KY'),
    'murray state': ('Murray', 'KY'),
    'northern kentucky': ('Highland Heights', 'KY'),
    'louisiana-monroe': ('Monroe', 'LA'),
    'louisiana tech university': ('Ruston', 'LA'),
    'mcneese state': ('Lake Charles', 'LA'),
    'nicholls state': ('Thibodaux', 'LA'),
    'southeastern louisiana': ('Hammond', 'LA'),
    'northwestern state': ('Natchitoches', 'LA'),
    'grambling': ('Grambling', 'LA'),
    'southern': ('Baton Rouge', 'LA'),
    'new orleans': ('New Orleans', 'LA'),
    'central arkansas': ('Conway', 'AR'),
    'arkansas state': ('Jonesboro', 'AR'),
    'arkansas-little rock': ('Little Rock', 'AR'),
    'arkansas-pine bluff': ('Pine Bluff', 'AR'),
    'arkansas tech': ('Russellville', 'AR'),
    'harding': ('Searcy', 'AR'),
    'missouri state university': ('Springfield', 'MO'),
    'missouri-kansas city': ('Kansas City', 'MO'),
    'umkc': ('Kansas City', 'MO'),
    'saint louis': ('St. Louis', 'MO'),
    'southeast missouri state': ('Cape Girardeau', 'MO'),
    'southwest missouri state': ('Springfield', 'MO'),
    'central missouri': ('Warrensburg', 'MO'),
    'northwest missouri state': ('Maryville', 'MO'),
    'missouri southern': ('Joplin', 'MO'),
    'missouri western': ('St. Joseph', 'MO'),
    'truman state': ('Kirksville', 'MO'),
    'oklahoma state university': ('Stillwater', 'OK'),
    'oral roberts university': ('Tulsa', 'OK'),
    'tulsa': ('Tulsa', 'OK'),
    'oklahoma city university': ('Oklahoma City', 'OK'),
    'central oklahoma': ('Edmond', 'OK'),
    'east central oklahoma': ('Ada', 'OK'),
    'northeastern state': ('Tahlequah', 'OK'),
    'cameron': ('Lawton', 'OK'),
    'wichita state (ks)': ('Wichita', 'KS'),
    'emporia state': ('Emporia', 'KS'),
    'fort hays state': ('Hays', 'KS'),
    'pittsburg state': ('Pittsburg', 'KS'),
    'washburn': ('Topeka', 'KS'),
    'nebraska-omaha': ('Omaha', 'NE'),
    'nebraska-kearney': ('Kearney', 'NE'),
    'creighton university': ('Omaha', 'NE'),
    'north dakota state': ('Fargo', 'ND'),
    'south dakota state': ('Brookings', 'SD'),
    'north dakota': ('Grand Forks', 'ND'),
    'south dakota': ('Vermillion', 'SD'),
    'iowa state': ('Ames', 'IA'),
    'northern iowa': ('Cedar Falls', 'IA'),
    'drake': ('Des Moines', 'IA'),
    'minnesota state': ('Mankato', 'MN'),
    'minnesota-duluth': ('Duluth', 'MN'),
    'st. cloud state': ('St. Cloud', 'MN'),
    'wisconsin-milwaukee': ('Milwaukee', 'WI'),
    'wisconsin-oshkosh': ('Oshkosh', 'WI'),
    'wisconsin-whitewater': ('Whitewater', 'WI'),
    'marquette': ('Milwaukee', 'WI'),
    'colorado': ('Boulder', 'CO'),
    'colorado state': ('Fort Collins', 'CO'),
    'northern colorado': ('Greeley', 'CO'),
    'denver': ('Denver', 'CO'),
    'air force academy': ('Colorado Springs', 'CO'),
    'metro state denver': ('Denver', 'CO'),
    'wyoming': ('Laramie', 'WY'),
    'montana': ('Missoula', 'MT'),
    'montana state': ('Bozeman', 'MT'),
    'idaho': ('Moscow', 'ID'),
    'idaho state': ('Pocatello', 'ID'),
    'boise state': ('Boise', 'ID'),
    'utah state': ('Logan', 'UT'),
    'utah valley': ('Orem', 'UT'),
    'weber state': ('Ogden', 'UT'),
    'southern utah': ('Cedar City', 'UT'),
    'dixie state': ('St. George', 'UT'),
    'new mexico state': ('Las Cruces', 'NM'),
    'nevada-las vegas': ('Las Vegas', 'NV'),
    'nevada-reno': ('Reno', 'NV'),
    'seattle': ('Seattle', 'WA'),
    'seattle university': ('Seattle', 'WA'),
    'eastern washington': ('Cheney', 'WA'),
    'central washington': ('Ellensburg', 'WA'),
    'western washington': ('Bellingham', 'WA'),
    'portland state': ('Portland', 'OR'),
    'oregon tech': ('Klamath Falls', 'OR'),
    'hawaii-hilo': ('Hilo', 'HI'),
    'hawaii-manoa': ('Honolulu', 'HI'),
    'hawaii pacific': ('Honolulu', 'HI'),
    'alaska-anchorage': ('Anchorage', 'AK'),
    'alaska-fairbanks': ('Fairbanks', 'AK'),

    # --- fourth tranche: exact spellings from round-3 punch-list ---
    'unc-greensboro': ('Greensboro', 'NC'),
    'william and mary': ('Williamsburg', 'VA'),
    'florida gateway': ('Lake City', 'FL'),
    'se louisiana': ('Hammond', 'LA'),
    'middle georgia': ('Cochran', 'GA'),
    'wabash valley college': ('Mount Carmel', 'IL'),
    'broward college': ('Fort Lauderdale', 'FL'),
    'utah tech': ('St. George', 'UT'),
    'western oklahoma state': ('Altus', 'OK'),
    'fresno city': ('Fresno', 'CA'),
    'edmonds cc': ('Lynnwood', 'WA'),
    'spartanburg methodist': ('Spartanburg', 'SC'),
    'grossmont': ('El Cajon', 'CA'),
    'la pierce': ('Woodland Hills', 'CA'),       # LA Pierce College
    'southern idaho': ('Twin Falls', 'ID'),      # College of Southern Idaho
    'tallahassee cc': ('Tallahassee', 'FL'),
    'cuesta college': ('San Luis Obispo', 'CA'),
    'franklin pierce': ('Rindge', 'NH'),
    'iowa western cc': ('Council Bluffs', 'IA'),
    'va military inst.': ('Lexington', 'VA'),     # VMI
    'modesto junior college': ('Modesto', 'CA'),
    'bellevue cc': ('Bellevue', 'WA'),
    'mount olive': ('Mount Olive', 'NC'),
    'delta state': ('Cleveland', 'MS'),
    'cal poly pomona': ('Pomona', 'CA'),
    # a batch more mid-value programs likely still in the tail
    'jacksonville university': ('Jacksonville', 'FL'),
    'north carolina a&t': ('Greensboro', 'NC'),
    'north carolina central': ('Durham', 'NC'),
    'winston-salem state': ('Winston-Salem', 'NC'),
    'fayetteville state': ('Fayetteville', 'NC'),
    'barton': ('Wilson', 'NC'),
    'catawba': ('Salisbury', 'NC'),
    'pfeiffer': ('Misenheimer', 'NC'),
    'queens (nc)': ('Charlotte', 'NC'),
    'lenoir-rhyne': ('Hickory', 'NC'),
    'wingate': ('Wingate', 'NC'),
    'mars hill': ('Mars Hill', 'NC'),
    'pembroke': ('Pembroke', 'NC'),
    'louisburg college': ('Louisburg', 'NC'),
    'spartanburg cc': ('Spartanburg', 'SC'),
    'anderson (sc)': ('Anderson', 'SC'),
    'newberry': ('Newberry', 'SC'),
    'lander': ('Greenwood', 'SC'),
    'north greenville': ('Tigerville', 'SC'),
    'usc sumter': ('Sumter', 'SC'),
    'usc beaufort': ('Bluffton', 'SC'),
    'young harris': ('Young Harris', 'GA'),
    'gordon state': ('Barnesville', 'GA'),
    'darton state': ('Albany', 'GA'),
    'abraham baldwin': ('Tifton', 'GA'),
    'south georgia': ('Douglas', 'GA'),
    'georgia perimeter': ('Clarkston', 'GA'),
    'chattahoochee valley': ('Phenix City', 'AL'),
    'wallace state': ('Hanceville', 'AL'),
    'wallace cc': ('Dothan', 'AL'),
    'calhoun cc': ('Tanner', 'AL'),
    'lawson state': ('Birmingham', 'AL'),
    'shelton state': ('Tuscaloosa', 'AL'),
    'bishop state': ('Mobile', 'AL'),
    'faulkner': ('Montgomery', 'AL'),
    'montevallo': ('Montevallo', 'AL'),
    'north alabama': ('Florence', 'AL'),
    'west alabama': ('Livingston', 'AL'),
    'alabama state': ('Montgomery', 'AL'),
    'alabama a&m': ('Normal', 'AL'),
    'itawamba cc': ('Fulton', 'MS'),
    'itawamba': ('Fulton', 'MS'),
    'jones county jc': ('Ellisville', 'MS'),
    'jones county': ('Ellisville', 'MS'),
    'hinds cc': ('Raymond', 'MS'),
    'hinds': ('Raymond', 'MS'),
    'east mississippi cc': ('Scooba', 'MS'),
    'northeast mississippi cc': ('Booneville', 'MS'),
    'northwest mississippi cc': ('Senatobia', 'MS'),
    'pearl river cc': ('Poplarville', 'MS'),
    'copiah-lincoln cc': ('Wesson', 'MS'),
    'holmes cc': ('Goodman', 'MS'),
    'mississippi delta cc': ('Moorhead', 'MS'),
    'mississippi gulf coast': ('Perkinston', 'MS'),
    'gulf coast (ms)': ('Perkinston', 'MS'),
    'mississippi college': ('Clinton', 'MS'),
    'mississippi valley state': ('Itta Bena', 'MS'),
    'jackson state': ('Jackson', 'MS'),
    'william carey': ('Hattiesburg', 'MS'),
    'lsu-eunice': ('Eunice', 'LA'),
    'lsu eunice': ('Eunice', 'LA'),
    'lsu-shreveport': ('Shreveport', 'LA'),
    'delgado cc': ('New Orleans', 'LA'),
    'bossier parish cc': ('Bossier City', 'LA'),
    'louisiana college': ('Pineville', 'LA'),
    'loyola (la)': ('New Orleans', 'LA'),
    'xavier (la)': ('New Orleans', 'LA'),
    'centenary': ('Shreveport', 'LA'),
    'crowder college': ('Neosho', 'MO'),
    'crowder': ('Neosho', 'MO'),
    'jefferson college': ('Hillsboro', 'MO'),
    'st. louis cc': ('St. Louis', 'MO'),
    'st. charles cc': ('Cottleville', 'MO'),
    'three rivers cc': ('Poplar Bluff', 'MO'),
    'east central college': ('Union', 'MO'),
    'mineral area college': ('Park Hills', 'MO'),
    'moberly area cc': ('Moberly', 'MO'),
    'state fair cc': ('Sedalia', 'MO'),
    'wentworth': ('Lexington', 'MO'),
    'rose state': ('Midwest City', 'OK'),
    'seminole state (ok)': ('Seminole', 'OK'),
    'murray state (ok)': ('Tishomingo', 'OK'),
    'eastern oklahoma state': ('Wilburton', 'OK'),
    'northeastern oklahoma a&m': ('Miami', 'OK'),
    'redlands cc': ('El Reno', 'OK'),
    'western oklahoma': ('Altus', 'OK'),
    'carl albert state': ('Poteau', 'OK'),
    'northern oklahoma': ('Tonkawa', 'OK'),
    'oklahoma panhandle state': ('Goodwell', 'OK'),
    'southeastern oklahoma state': ('Durant', 'OK'),
    'southwestern oklahoma state': ('Weatherford', 'OK'),
    'central oklahoma university': ('Edmond', 'OK'),
    'coffeyville': ('Coffeyville', 'KS'),
    'independence cc': ('Independence', 'KS'),
    'allen county cc': ('Iola', 'KS'),
    'colby cc': ('Colby', 'KS'),
    'pratt cc': ('Pratt', 'KS'),
    'kansas city kansas cc': ('Kansas City', 'KS'),
    'highland cc': ('Highland', 'KS'),
    'fort scott cc': ('Fort Scott', 'KS'),
    'cloud county cc': ('Concordia', 'KS'),
    'ottawa': ('Ottawa', 'KS'),
    'mcpherson': ('McPherson', 'KS'),
    'bethany (ks)': ('Lindsborg', 'KS'),
    'sterling': ('Sterling', 'KS'),
    'tabor': ('Hillsboro', 'KS'),
    'southwestern (ks)': ('Winfield', 'KS'),
    'friends': ('Wichita', 'KS'),
    'newman': ('Wichita', 'KS'),
    'iowa central cc': ('Fort Dodge', 'IA'),
    'iowa lakes cc': ('Estherville', 'IA'),
    'kirkwood cc': ('Cedar Rapids', 'IA'),
    'des moines area cc': ('Ankeny', 'IA'),
    'indian hills cc': ('Ottumwa', 'IA'),
    'ellsworth cc': ('Iowa Falls', 'IA'),
    'southeastern cc (ia)': ('West Burlington', 'IA'),
    'muscatine cc': ('Muscatine', 'IA'),
    'scott cc': ('Bettendorf', 'IA'),
    'grand view': ('Des Moines', 'IA'),
    'dallas baptist university': ('Dallas', 'TX'),
    'lsu health': ('New Orleans', 'LA'),
    'cal poly pomona university': ('Pomona', 'CA'),

    # --- fifth tranche: round-4 punch-list, exact spellings + variant fixes ---
    'northeast texas cc': ('Mount Pleasant', 'TX'),
    'california baptist': ('Riverside', 'CA'),
    'illinois-chicago': ('Chicago', 'IL'),
    'eastern ok st': ('Wilburton', 'OK'),
    'col of canyons': ('Santa Clarita', 'CA'),
    'barry': ('Miami Shores', 'FL'),
    'galveston': ('Galveston', 'TX'),
    'bowling green state': ('Bowling Green', 'OH'),
    'santa fe cc': ('Gainesville', 'FL'),
    'hill college': ('Hillsboro', 'TX'),
    'milwaukee': ('Milwaukee', 'WI'),           # UW-Milwaukee
    'young harris college': ('Young Harris', 'GA'),
    'louisburg': ('Louisburg', 'NC'),
    'kishwaukee': ('Malta', 'IL'),
    'el paso cc': ('El Paso', 'TX'),
    'golden west': ('Huntington Beach', 'CA'),
    'british columbia': ('Vancouver', 'BC'),
    'cerritos': ('Norwalk', 'CA'),
    'bryant university': ('Smithfield', 'RI'),
    'freed-hardeman': ('Henderson', 'TN'),
    'lee university': ('Cleveland', 'TN'),
    'ark-little rock': ('Little Rock', 'AR'),
    'mesa state college': ('Grand Junction', 'CO'),
    'alabama-birmingham': ('Birmingham', 'AL'),
    'cumberland': ('Lebanon', 'TN'),
    # a final batch of recognizable mid-tail programs
    'san diego christian': ('Santee', 'CA'),
    'the master\'s': ('Santa Clarita', 'CA'),
    'vanguard': ('Costa Mesa', 'CA'),
    'westmont': ('Santa Barbara', 'CA'),
    'fresno pacific': ('Fresno', 'CA'),
    'notre dame de namur': ('Belmont', 'CA'),
    'dominican (ca)': ('San Rafael', 'CA'),
    'holy names': ('Oakland', 'CA'),
    'academy of art': ('San Francisco', 'CA'),
    'cal state channel islands': ('Camarillo', 'CA'),
    'college of idaho': ('Caldwell', 'ID'),
    'lewis-clark': ('Lewiston', 'ID'),
    'northwest nazarene': ('Nampa', 'ID'),
    'carroll (mt)': ('Helena', 'MT'),
    'montana state-billings': ('Billings', 'MT'),
    'rocky mountain': ('Billings', 'MT'),
    'great falls': ('Great Falls', 'MT'),
    'western oregon': ('Monmouth', 'OR'),
    'southern oregon': ('Ashland', 'OR'),
    'concordia (or)': ('Portland', 'OR'),
    'george fox': ('Newberg', 'OR'),
    'linfield': ('McMinnville', 'OR'),
    'pacific (or)': ('Forest Grove', 'OR'),
    'willamette': ('Salem', 'OR'),
    'lewis & clark (or)': ('Portland', 'OR'),
    'saint martin\'s': ('Lacey', 'WA'),
    'central washington university': ('Ellensburg', 'WA'),
    'saint mary\'s (tx)': ('San Antonio', 'TX'),
    'texas a&m-commerce': ('Commerce', 'TX'),
    'texas woman\'s': ('Denton', 'TX'),
    'lubbock christian': ('Lubbock', 'TX'),
    'wayland baptist': ('Plainview', 'TX'),
    'mcmurry': ('Abilene', 'TX'),
    'hardin-simmons': ('Abilene', 'TX'),
    'howard payne': ('Brownwood', 'TX'),
    'concordia (tx)': ('Austin', 'TX'),
    'st. edward\'s': ('Austin', 'TX'),
    'st. mary\'s (tx)': ('San Antonio', 'TX'),
    'texas lutheran': ('Seguin', 'TX'),
    'trinity (tx)': ('San Antonio', 'TX'),
    'schreiner': ('Kerrville', 'TX'),
    'east texas baptist': ('Marshall', 'TX'),
    'ut permian basin': ('Odessa', 'TX'),
    'ut tyler': ('Tyler', 'TX'),
    'ut dallas': ('Richardson', 'TX'),
    'kilgore college': ('Kilgore', 'TX'),
    'tyler junior college': ('Tyler', 'TX'),
    'trinity valley cc': ('Athens', 'TX'),
    'ranger college': ('Ranger', 'TX'),
    'cisco college': ('Cisco', 'TX'),
    'frank phillips': ('Borger', 'TX'),
    'clarendon college': ('Clarendon', 'TX'),
    'coastal bend college': ('Beeville', 'TX'),
    'laredo college': ('Laredo', 'TX'),
    'del mar college': ('Corpus Christi', 'TX'),
    'san antonio college': ('San Antonio', 'TX'),
    'st. philip\'s college': ('San Antonio', 'TX'),
    'palo alto college': ('San Antonio', 'TX'),
    'victoria college': ('Victoria', 'TX'),
    'lee college': ('Baytown', 'TX'),
    'lon morris': ('Jacksonville', 'TX'),
    'jacksonville college': ('Jacksonville', 'TX'),
    'central texas college': ('Killeen', 'TX'),
    'hill': ('Hillsboro', 'TX'),
    'vernon college': ('Vernon', 'TX'),
    'north central texas': ('Gainesville', 'TX'),
    'collin county cc': ('McKinney', 'TX'),
    'collin college': ('McKinney', 'TX'),
    'brookhaven college': ('Farmers Branch', 'TX'),
    'eastfield college': ('Mesquite', 'TX'),
    'mountain view college': ('Dallas', 'TX'),
    'richland college': ('Dallas', 'TX'),
    'north lake college': ('Irving', 'TX'),
    'tarrant county college': ('Fort Worth', 'TX'),
    'illinois-chicago (uic)': ('Chicago', 'IL'),
    'lincoln college': ('Lincoln', 'IL'),
    'rend lake college': ('Ina', 'IL'),
    'shawnee cc': ('Ullin', 'IL'),
    'olney central': ('Olney', 'IL'),
    'lake land college': ('Mattoon', 'IL'),
    'danville area cc': ('Danville', 'IL'),
    'college of dupage': ('Glen Ellyn', 'IL'),
    'joliet junior college': ('Joliet', 'IL'),
    'moraine valley': ('Palos Hills', 'IL'),
    'south suburban': ('South Holland', 'IL'),
    'waubonsee cc': ('Sugar Grove', 'IL'),
    'mchenry county college': ('Crystal Lake', 'IL'),
    'rock valley college': ('Rockford', 'IL'),
    'sauk valley cc': ('Dixon', 'IL'),
    'black hawk college': ('Moline', 'IL'),
    'carl sandburg college': ('Galesburg', 'IL'),
    'spoon river college': ('Canton', 'IL'),
    'lincoln trail college': ('Robinson', 'IL'),

    # --- sixth tranche: large batch, round-5 punch-list + common tail ---
    'tennessee wesleyan college': ('Athens', 'TN'),
    'saint leo': ('Saint Leo', 'FL'),
    'mercyhurst': ('Erie', 'PA'),
    'lower columbia cc': ('Longview', 'WA'),
    'merced college': ('Merced', 'CA'),
    'georgia college & state': ('Milledgeville', 'GA'),
    'mobile': ('Mobile', 'AL'),
    'santiago canyon college': ('Orange', 'CA'),
    'central florida cc': ('Ocala', 'FL'),
    'southern arkansas': ('Magnolia', 'AR'),
    'siena college': ('Loudonville', 'NY'),
    'western nevada cc': ('Carson City', 'NV'),
    'lamar cc': ('Lamar', 'CO'),
    'eastern fl st': ('Melbourne', 'FL'),
    'shippensburg': ('Shippensburg', 'PA'),
    # eastern / midwest 4-year
    'kutztown': ('Kutztown', 'PA'),
    'west chester': ('West Chester', 'PA'),
    'millersville': ('Millersville', 'PA'),
    'bloomsburg': ('Bloomsburg', 'PA'),
    'east stroudsburg': ('East Stroudsburg', 'PA'),
    'indiana (pa)': ('Indiana', 'PA'),
    'california (pa)': ('California', 'PA'),
    'slippery rock': ('Slippery Rock', 'PA'),
    'edinboro': ('Edinboro', 'PA'),
    'clarion': ('Clarion', 'PA'),
    'gannon': ('Erie', 'PA'),
    'seton hill': ('Greensburg', 'PA'),
    'west virginia state': ('Institute', 'WV'),
    'west virginia wesleyan': ('Buckhannon', 'WV'),
    'fairmont state': ('Fairmont', 'WV'),
    'charleston (wv)': ('Charleston', 'WV'),
    'concord': ('Athens', 'WV'),
    'shepherd': ('Shepherdstown', 'WV'),
    'wheeling jesuit': ('Wheeling', 'WV'),
    'salem international': ('Salem', 'WV'),
    'davis & elkins': ('Elkins', 'WV'),
    'kentucky wesleyan': ('Owensboro', 'KY'),
    'bellarmine': ('Louisville', 'KY'),
    'campbellsville': ('Campbellsville', 'KY'),
    'cumberlands': ('Williamsburg', 'KY'),
    'pikeville': ('Pikeville', 'KY'),
    'lindsey wilson': ('Columbia', 'KY'),
    'georgetown (ky)': ('Georgetown', 'KY'),
    'thomas more': ('Crestview Hills', 'KY'),
    'brescia': ('Owensboro', 'KY'),
    'union (ky)': ('Barbourville', 'KY'),
    'tennessee state': ('Nashville', 'TN'),
    'tennessee wesleyan': ('Athens', 'TN'),
    'trevecca nazarene': ('Nashville', 'TN'),
    'union (tn)': ('Jackson', 'TN'),
    'carson-newman': ('Jefferson City', 'TN'),
    'tusculum': ('Greeneville', 'TN'),
    'king (tn)': ('Bristol', 'TN'),
    'milligan': ('Milligan', 'TN'),
    'bryan': ('Dayton', 'TN'),
    'bethel (tn)': ('McKenzie', 'TN'),
    'christian brothers': ('Memphis', 'TN'),
    'rhodes': ('Memphis', 'TN'),
    'sewanee': ('Sewanee', 'TN'),
    'columbia state cc': ('Columbia', 'TN'),
    'cleveland state cc': ('Cleveland', 'TN'),
    'chattanooga state cc': ('Chattanooga', 'TN'),
    'motlow state cc': ('Tullahoma', 'TN'),
    'jackson state cc': ('Jackson', 'TN'),
    'roane state cc': ('Harriman', 'TN'),
    'dyersburg state': ('Dyersburg', 'TN'),
    'volunteer state': ('Gallatin', 'TN'),
    'nashville state': ('Nashville', 'TN'),
    'southwest tennessee': ('Memphis', 'TN'),
    'flagler': ('St. Augustine', 'FL'),
    'lynn': ('Boca Raton', 'FL'),
    'rollins': ('Winter Park', 'FL'),
    'eckerd': ('St. Petersburg', 'FL'),
    'palm beach atlantic': ('West Palm Beach', 'FL'),
    'saint thomas (fl)': ('Miami Gardens', 'FL'),
    'florida memorial': ('Miami Gardens', 'FL'),
    'edward waters': ('Jacksonville', 'FL'),
    'warner (fl)': ('Lake Wales', 'FL'),
    'webber international': ('Babson Park', 'FL'),
    'ave maria': ('Ave Maria', 'FL'),
    'florida tech': ('Melbourne', 'FL'),
    'daytona state': ('Daytona Beach', 'FL'),
    'lake sumter state': ('Leesburg', 'FL'),
    'south florida state': ('Avon Park', 'FL'),
    'college of central florida': ('Ocala', 'FL'),
    'pasco-hernando state': ('New Port Richey', 'FL'),
    'st. johns river state': ('Palatka', 'FL'),
    'florida national': ('Hialeah', 'FL'),
    'miami dade college': ('Miami', 'FL'),
    'valencia college': ('Orlando', 'FL'),
    'eastern florida state': ('Melbourne', 'FL'),
    'broward': ('Fort Lauderdale', 'FL'),
    'palm beach': ('Lake Worth', 'FL'),
    'lake city cc': ('Lake City', 'FL'),
    'central alabama cc': ('Alexander City', 'AL'),
    'gadsden state': ('Gadsden', 'AL'),
    'jefferson state cc': ('Birmingham', 'AL'),
    'jefferson davis cc': ('Brewton', 'AL'),
    'snead state': ('Boaz', 'AL'),
    'southern union state': ('Wadley', 'AL'),
    'enterprise state': ('Enterprise', 'AL'),
    'coastal alabama': ('Bay Minette', 'AL'),
    'marion military': ('Marion', 'AL'),
    'spring hill': ('Mobile', 'AL'),
    'huntingdon': ('Montgomery', 'AL'),
    'miles': ('Fairfield', 'AL'),
    'tuskegee': ('Tuskegee', 'AL'),
    'auburn-montgomery': ('Montgomery', 'AL'),
    'georgia gwinnett': ('Lawrenceville', 'GA'),
    'clayton state': ('Morrow', 'GA'),
    'georgia southwestern': ('Americus', 'GA'),
    'fort valley state': ('Fort Valley', 'GA'),
    'albany state': ('Albany', 'GA'),
    'paine': ('Augusta', 'GA'),
    'shorter': ('Rome', 'GA'),
    'berry': ('Mount Berry', 'GA'),
    'reinhardt': ('Waleska', 'GA'),
    'brewton-parker': ('Mount Vernon', 'GA'),
    'thomas (ga)': ('Thomasville', 'GA'),
    'point (ga)': ('West Point', 'GA'),
    'life (ga)': ('Marietta', 'GA'),
    'georgia highlands': ('Rome', 'GA'),
    'andrew college': ('Cuthbert', 'GA'),
    'east georgia state': ('Swainsboro', 'GA'),
    'gordon': ('Barnesville', 'GA'),
    'san diego mesa college': ('San Diego', 'CA'),
    'imperial valley college': ('Imperial', 'CA'),
    'mira costa': ('Oceanside', 'CA'),
    'mt. san jacinto college': ('San Jacinto', 'CA'),
    'college of the desert': ('Palm Desert', 'CA'),
    'victor valley': ('Victorville', 'CA'),
    'barstow college': ('Barstow', 'CA'),
    'crafton hills': ('Yucaipa', 'CA'),
    'copper mountain': ('Joshua Tree', 'CA'),
    'reedley college': ('Reedley', 'CA'),
    'west hills college': ('Coalinga', 'CA'),
    'porterville college': ('Porterville', 'CA'),
    'taft college': ('Taft', 'CA'),
    'merced': ('Merced', 'CA'),
    'modesto': ('Modesto', 'CA'),
    'columbia college (ca)': ('Sonora', 'CA'),
    'san joaquin delta college': ('Stockton', 'CA'),
    'butte college': ('Oroville', 'CA'),
    'shasta college': ('Redding', 'CA'),
    'feather river': ('Quincy', 'CA'),
    'lassen college': ('Susanville', 'CA'),
    'yuba college': ('Marysville', 'CA'),
    'napa valley college': ('Napa', 'CA'),
    'solano cc': ('Fairfield', 'CA'),
    'contra costa college': ('San Pablo', 'CA'),
    'los medanos': ('Pittsburg', 'CA'),
    'laney college': ('Oakland', 'CA'),
    'merritt college': ('Oakland', 'CA'),
    'ohlone college': ('Fremont', 'CA'),
    'las positas': ('Livermore', 'CA'),
    'foothill college': ('Los Altos Hills', 'CA'),
    'de anza college': ('Cupertino', 'CA'),
    'west valley college': ('Saratoga', 'CA'),
    'mission college': ('Santa Clara', 'CA'),
    'gavilan college': ('Gilroy', 'CA'),
    'hartnell college': ('Salinas', 'CA'),
    'monterey peninsula': ('Monterey', 'CA'),
    'cabrillo college': ('Aptos', 'CA'),
    'canada college': ('Redwood City', 'CA'),
    'skyline college': ('San Bruno', 'CA'),
    'evergreen valley': ('San Jose', 'CA'),
    'san jose city college': ('San Jose', 'CA'),

    # --- final cleanup tranche ---
    'glendale cc az': ('Glendale', 'AZ'),
    'mount san antonio college': ('Walnut', 'CA'),
    'col of sequoias': ('Visalia', 'CA'),
    'birmingham-southern': ('Birmingham', 'AL'),
    'le moyne': ('Syracuse', 'NY'),
    'fsc at jacksonville': ('Jacksonville', 'FL'),
    'mt. hood cc': ('Gresham', 'OR'),
    'sj delta college': ('Stockton', 'CA'),
    'columbia basin college': ('Pasco', 'WA'),
    'west florida': ('Pensacola', 'FL'),
    'chico state': ('Chico', 'CA'),
    "master's": ('Santa Clarita', 'CA'),
    'arkansas-fort smith': ('Fort Smith', 'AR'),
    'pasco-hernando cc': ('New Port Richey', 'FL'),
    'brookdale cc': ('Lincroft', 'NJ'),
    'utrgv': ('Edinburg', 'TX'),
    'midland col': ('Midland', 'TX'),
    'oklahoma baptist': ('Shawnee', 'OK'),
    'long beach cc': ('Long Beach', 'CA'),
    'pitt cc': ('Winterville', 'NC'),
    'ga southern armstrong': ('Savannah', 'GA'),
    'daytona beach cc': ('Daytona Beach', 'FL'),
    'green river cc': ('Auburn', 'WA'),
    'missouri baptist': ('St. Louis', 'MO'),
    'salt lake cc': ('Salt Lake City', 'UT'),
    # more recognizable tail
    'wallace-hanceville': ('Hanceville', 'AL'),
    'chico': ('Chico', 'CA'),
    'sonoma': ('Rohnert Park', 'CA'),
    'cal state fresno': ('Fresno', 'CA'),
    'cal state bakersfield university': ('Bakersfield', 'CA'),
    'lubbock christian university': ('Lubbock', 'TX'),
    'st. thomas (mn)': ('St. Paul', 'MN'),
    'st. thomas': ('St. Paul', 'MN'),
    'concordia (mn)': ('Moorhead', 'MN'),
    'bethel (mn)': ('St. Paul', 'MN'),
    'gustavus adolphus': ('St. Peter', 'MN'),
    'st. olaf': ('Northfield', 'MN'),
    'carleton': ('Northfield', 'MN'),
    'macalester': ('St. Paul', 'MN'),
    'augsburg': ('Minneapolis', 'MN'),
    'hamline': ('St. Paul', 'MN'),
    'winona state': ('Winona', 'MN'),
    'mankato': ('Mankato', 'MN'),
    'bemidji state': ('Bemidji', 'MN'),
    'minnesota state-moorhead': ('Moorhead', 'MN'),
    'southwest minnesota state': ('Marshall', 'MN'),
    'rochester cc': ('Rochester', 'MN'),
    'dakota county tech': ('Rosemount', 'MN'),
    'century college': ('White Bear Lake', 'MN'),
    'normandale': ('Bloomington', 'MN'),
    'minnesota west': ('Worthington', 'MN'),
    'iowa western': ('Council Bluffs', 'IA'),
    'southwestern (ia)': ('Creston', 'IA'),
    'north iowa area cc': ('Mason City', 'IA'),
    'northeast iowa cc': ('Calmar', 'IA'),
    'dmacc': ('Ankeny', 'IA'),
    'marshalltown cc': ('Marshalltown', 'IA'),
    'clinton cc (ia)': ('Clinton', 'IA'),
    'wisconsin-la crosse': ('La Crosse', 'WI'),
    'wisconsin-stevens point': ('Stevens Point', 'WI'),
    'wisconsin-eau claire': ('Eau Claire', 'WI'),
    'wisconsin-platteville': ('Platteville', 'WI'),
    'wisconsin-stout': ('Menomonie', 'WI'),
    'wisconsin-parkside': ('Kenosha', 'WI'),
    'wisconsin-green bay': ('Green Bay', 'WI'),
    'carthage': ('Kenosha', 'WI'),
    'concordia (wi)': ('Mequon', 'WI'),
    'st. norbert': ('De Pere', 'WI'),
    'wisconsin lutheran': ('Milwaukee', 'WI'),
    'madison college': ('Madison', 'WI'),
    'milwaukee area tech': ('Milwaukee', 'WI'),
    'grand rapids cc': ('Grand Rapids', 'MI'),
    'lansing cc': ('Lansing', 'MI'),
    'henry ford college': ('Dearborn', 'MI'),
    'macomb cc': ('Warren', 'MI'),
    'schoolcraft college': ('Livonia', 'MI'),
    'oakland cc': ('Bloomfield Hills', 'MI'),
    'wayne county cc': ('Detroit', 'MI'),
    'delta college': ('University Center', 'MI'),
    'mott cc': ('Flint', 'MI'),
    'kellogg cc': ('Battle Creek', 'MI'),
    'kalamazoo valley cc': ('Kalamazoo', 'MI'),
    'jackson college': ('Jackson', 'MI'),
    'lake michigan college': ('Benton Harbor', 'MI'),
    'muskegon cc': ('Muskegon', 'MI'),
    'grand valley state': ('Allendale', 'MI'),
    'saginaw valley state': ('University Center', 'MI'),
    'ferris state': ('Big Rapids', 'MI'),
    'hope': ('Holland', 'MI'),
    'calvin': ('Grand Rapids', 'MI'),
    'aquinas (mi)': ('Grand Rapids', 'MI'),
    'davenport': ('Grand Rapids', 'MI'),
    'northwood': ('Midland', 'MI'),
    'madonna': ('Livonia', 'MI'),
    'siena heights': ('Adrian', 'MI'),
    'concordia (mi)': ('Ann Arbor', 'MI'),
    'lawrence tech': ('Southfield', 'MI'),
    'lake superior state': ('Sault Ste. Marie', 'MI'),
    'northern michigan': ('Marquette', 'MI'),
    'michigan tech': ('Houghton', 'MI'),
    'owens cc': ('Toledo', 'OH'),
    'sinclair cc': ('Dayton', 'OH'),
    'cuyahoga cc': ('Cleveland', 'OH'),
    'columbus state cc': ('Columbus', 'OH'),
    'lakeland cc': ('Kirtland', 'OH'),
    'lorain county cc': ('Elyria', 'OH'),
    'clark state': ('Springfield', 'OH'),
    'shawnee state': ('Portsmouth', 'OH'),
    'walsh': ('North Canton', 'OH'),
    'malone': ('Canton', 'OH'),
    'mount union': ('Alliance', 'OH'),
    'ashland': ('Ashland', 'OH'),
    'findlay': ('Findlay', 'OH'),
    'tiffin': ('Tiffin', 'OH'),
    'urbana': ('Urbana', 'OH'),
    'cedarville': ('Cedarville', 'OH'),
    'wilmington (oh)': ('Wilmington', 'OH'),
    'otterbein': ('Westerville', 'OH'),
    'capital': ('Columbus', 'OH'),
    'ohio dominican': ('Columbus', 'OH'),
    'muskingum': ('New Concord', 'OH'),
    'marietta': ('Marietta', 'OH'),
    'baldwin wallace': ('Berea', 'OH'),
    'john carroll': ('University Heights', 'OH'),
    'lake erie': ('Painesville', 'OH'),
    'notre dame (oh)': ('South Euclid', 'OH'),
    'wittenberg': ('Springfield', 'OH'),
    'wooster': ('Wooster', 'OH'),
    'denison': ('Granville', 'OH'),
    'kenyon': ('Gambier', 'OH'),
    'oberlin': ('Oberlin', 'OH'),
    'defiance': ('Defiance', 'OH'),
    'bluffton': ('Bluffton', 'OH'),
    'heidelberg': ('Tiffin', 'OH'),

    # --- seventh tranche: large batch, round-7 punch-list + national tail ---
    'nc a&t state': ('Greensboro', 'NC'),
    'ne oklahoma am': ('Miami', 'OK'),
    'uw whitewater': ('Whitewater', 'WI'),
    'rowan-gloucester': ('Sewell', 'NJ'),
    'north central tx': ('Gainesville', 'TX'),
    'california lutheran': ('Thousand Oaks', 'CA'),
    'trinidad state': ('Trinidad', 'CO'),
    'lethbridge cc': ('Lethbridge', 'AB'),
    'east los angeles college': ('Monterey Park', 'CA'),
    'oxnard college': ('Oxnard', 'CA'),
    'francis marion': ('Florence', 'SC'),
    'southern new hampshire': ('Manchester', 'NH'),
    'pace': ('Pleasantville', 'NY'),
    'charleston southern': ('Charleston', 'SC'),
    'college of marin': ('Kentfield', 'CA'),
    'concordia university': ('Irvine', 'CA'),      # ambiguous; CU Irvine baseball
    'limestone': ('Gaffney', 'SC'),
    'massachusetts-lowell': ('Lowell', 'MA'),
    'everett cc': ('Everett', 'WA'),
    'florida sw': ('Fort Myers', 'FL'),
    'southern poly': ('Marietta', 'GA'),
    'glendale cc ca': ('Glendale', 'CA'),
    'chattahoochee val': ('Phenix City', 'AL'),
    'st. johns river cc': ('Palatka', 'FL'),
    'madison tech': ('Madison', 'WI'),
    # NAIA / small 4-year across regions
    'st. ambrose': ('Davenport', 'IA'),
    'graceland': ('Lamoni', 'IA'),
    'william penn': ('Oskaloosa', 'IA'),
    'mount mercy': ('Cedar Rapids', 'IA'),
    'clarke': ('Dubuque', 'IA'),
    'loras': ('Dubuque', 'IA'),
    'central (ia)': ('Pella', 'IA'),
    'wartburg': ('Waverly', 'IA'),
    'coe': ('Cedar Rapids', 'IA'),
    'cornell (ia)': ('Mount Vernon', 'IA'),
    'buena vista': ('Storm Lake', 'IA'),
    'simpson (ia)': ('Indianola', 'IA'),
    'dordt': ('Sioux Center', 'IA'),
    'northwestern (ia)': ('Orange City', 'IA'),
    'morningside': ('Sioux City', 'IA'),
    'briar cliff': ('Sioux City', 'IA'),
    'dakota wesleyan': ('Mitchell', 'SD'),
    'augustana (sd)': ('Sioux Falls', 'SD'),
    'sioux falls': ('Sioux Falls', 'SD'),
    'black hills state': ('Spearfish', 'SD'),
    'jamestown': ('Jamestown', 'ND'),
    'mayville state': ('Mayville', 'ND'),
    'valley city state': ('Valley City', 'ND'),
    'minot state': ('Minot', 'ND'),
    'dickinson state': ('Dickinson', 'ND'),
    'bismarck state': ('Bismarck', 'ND'),
    'peru state': ('Peru', 'NE'),
    'wayne state (ne)': ('Wayne', 'NE'),
    'chadron state': ('Chadron', 'NE'),
    'doane': ('Crete', 'NE'),
    'hastings': ('Hastings', 'NE'),
    'concordia (ne)': ('Seward', 'NE'),
    'midland (ne)': ('Fremont', 'NE'),
    'bellevue (ne)': ('Bellevue', 'NE'),
    'nebraska wesleyan': ('Lincoln', 'NE'),
    'york (ne)': ('York', 'NE'),
    'college of saint mary': ('Omaha', 'NE'),
    'metropolitan cc (ne)': ('Omaha', 'NE'),
    'southeast cc (ne)': ('Lincoln', 'NE'),
    'central cc (ne)': ('Grand Island', 'NE'),
    'western nebraska cc': ('Scottsbluff', 'NE'),
    'mid-plains cc': ('North Platte', 'NE'),
    'northeast cc (ne)': ('Norfolk', 'NE'),
    'benedictine (ks)': ('Atchison', 'KS'),
    'baker (ks)': ('Baldwin City', 'KS'),
    'kansas wesleyan': ('Salina', 'KS'),
    'bethel college (ks)': ('North Newton', 'KS'),
    'central christian (ks)': ('McPherson', 'KS'),
    'ottawa university': ('Ottawa', 'KS'),
    'st. mary (ks)': ('Leavenworth', 'KS'),
    'avila': ('Kansas City', 'MO'),
    'rockhurst': ('Kansas City', 'MO'),
    'william jewell': ('Liberty', 'MO'),
    'missouri valley': ('Marshall', 'MO'),
    'central methodist': ('Fayette', 'MO'),
    'culver-stockton': ('Canton', 'MO'),
    'hannibal-lagrange': ('Hannibal', 'MO'),
    'evangel': ('Springfield', 'MO'),
    'drury': ('Springfield', 'MO'),
    'lincoln (mo)': ('Jefferson City', 'MO'),
    'harris-stowe': ('St. Louis', 'MO'),
    'maryville (mo)': ('St. Louis', 'MO'),
    'lindenwood': ('St. Charles', 'MO'),
    'fontbonne': ('St. Louis', 'MO'),
    'webster': ('St. Louis', 'MO'),
    'park (mo)': ('Parkville', 'MO'),
    'southwest baptist': ('Bolivar', 'MO'),
    'college of the ozarks': ('Point Lookout', 'MO'),
    'missouri s&t': ('Rolla', 'MO'),
    'quincy': ('Quincy', 'IL'),
    'mckendree': ('Lebanon', 'IL'),
    'greenville (il)': ('Greenville', 'IL'),
    'blackburn': ('Carlinville', 'IL'),
    'illinois college': ('Jacksonville', 'IL'),
    'monmouth (il)': ('Monmouth', 'IL'),
    'knox': ('Galesburg', 'IL'),
    'augustana (il)': ('Rock Island', 'IL'),
    'north central (il)': ('Naperville', 'IL'),
    'north park': ('Chicago', 'IL'),
    'benedictine (il)': ('Lisle', 'IL'),
    'lewis': ('Romeoville', 'IL'),
    'saint xavier': ('Chicago', 'IL'),
    'olivet nazarene': ('Bourbonnais', 'IL'),
    'trinity christian': ('Palos Heights', 'IL'),
    'judson (il)': ('Elgin', 'IL'),
    'aurora': ('Aurora', 'IL'),
    'elmhurst': ('Elmhurst', 'IL'),
    'wheaton (il)': ('Wheaton', 'IL'),
    'millikin': ('Decatur', 'IL'),
    'eureka': ('Eureka', 'IL'),
    'principia': ('Elsah', 'IL'),
    'rockford': ('Rockford', 'IL'),
    'st. francis (il)': ('Joliet', 'IL'),
    'indiana wesleyan': ('Marion', 'IN'),
    'huntington (in)': ('Huntington', 'IN'),
    'taylor': ('Upland', 'IN'),
    'anderson (in)': ('Anderson', 'IN'),
    'goshen': ('Goshen', 'IN'),
    'manchester (in)': ('North Manchester', 'IN'),
    'franklin (in)': ('Franklin', 'IN'),
    'hanover': ('Hanover', 'IN'),
    'depauw': ('Greencastle', 'IN'),
    'wabash': ('Crawfordsville', 'IN'),
    'earlham': ('Richmond', 'IN'),
    'rose-hulman': ('Terre Haute', 'IN'),
    'saint josephs (in)': ('Rensselaer', 'IN'),
    'marian (in)': ('Indianapolis', 'IN'),
    'university of indianapolis': ('Indianapolis', 'IN'),
    'saint francis (in)': ('Fort Wayne', 'IN'),
    'grace (in)': ('Winona Lake', 'IN'),
    'bethel (in)': ('Mishawaka', 'IN'),
    'oakland city': ('Oakland City', 'IN'),
    'vincennes': ('Vincennes', 'IN'),
    'ivy tech': ('Indianapolis', 'IN'),
    'st. mary-of-the-woods': ('Terre Haute', 'IN'),
    'trine': ('Angola', 'IN'),
    'malone university': ('Canton', 'OH'),
    'salem (wv)': ('Salem', 'WV'),
    'alderson broaddus': ('Philippi', 'WV'),
    'glenville state': ('Glenville', 'WV'),
    'west liberty': ('West Liberty', 'WV'),
    'bluefield state': ('Bluefield', 'WV'),
    'ohio valley': ('Vienna', 'WV'),
    'wheeling': ('Wheeling', 'WV'),
    'potomac state': ('Keyser', 'WV'),
    'wv tech': ('Montgomery', 'WV'),
    'bluefield (va)': ('Bluefield', 'VA'),
    'emory & henry': ('Emory', 'VA'),
    'ferrum': ('Ferrum', 'VA'),
    'averett': ('Danville', 'VA'),
    'lynchburg': ('Lynchburg', 'VA'),
    'randolph-macon': ('Ashland', 'VA'),
    'hampden-sydney': ('Hampden-Sydney', 'VA'),
    'roanoke': ('Salem', 'VA'),
    'bridgewater (va)': ('Bridgewater', 'VA'),
    'eastern mennonite': ('Harrisonburg', 'VA'),
    'shenandoah': ('Winchester', 'VA'),
    'mary washington': ('Fredericksburg', 'VA'),
    'christopher newport': ('Newport News', 'VA'),
    'virginia state': ('Petersburg', 'VA'),
    'virginia union': ('Richmond', 'VA'),
    'virginia wesleyan': ('Virginia Beach', 'VA'),
    'saint pauls': ('Lawrenceville', 'VA'),
    'chowan': ('Murfreesboro', 'NC'),
    'north carolina wesleyan': ('Rocky Mount', 'NC'),
    'methodist (nc)': ('Fayetteville', 'NC'),
    'st. andrews (nc)': ('Laurinburg', 'NC'),
    'belmont abbey': ('Belmont', 'NC'),
    'brevard': ('Brevard', 'NC'),
    'montreat': ('Montreat', 'NC'),
    'guilford': ('Greensboro', 'NC'),
    'greensboro': ('Greensboro', 'NC'),
    'high point university': ('High Point', 'NC'),
    'st. augustines': ('Raleigh', 'NC'),
    'shaw': ('Raleigh', 'NC'),
    'livingstone': ('Salisbury', 'NC'),
    'johnson c. smith': ('Charlotte', 'NC'),
    'winthrop university': ('Rock Hill', 'SC'),
    'coker': ('Hartsville', 'SC'),
    'erskine': ('Due West', 'SC'),
    'converse': ('Spartanburg', 'SC'),
    'anderson university (sc)': ('Anderson', 'SC'),
    'southern wesleyan': ('Central', 'SC'),
    'claflin': ('Orangeburg', 'SC'),
    'benedict': ('Columbia', 'SC'),
    'allen (sc)': ('Columbia', 'SC'),
    'voorhees': ('Denmark', 'SC'),
    'morris (sc)': ('Sumter', 'SC'),

    # --- eighth tranche: round-8 punch-list + wide tail ---
    'mercer county cc': ('West Windsor', 'NJ'),
    'new york tech': ('Old Westbury', 'NY'),
    'briarcliffe college': ('Bethpage', 'NY'),
    'houston christian': ('Houston', 'TX'),
    'csu-pueblo': ('Pueblo', 'CO'),
    'lurleen b. wallace': ('Andalusia', 'AL'),
    'regis': ('Denver', 'CO'),
    'ohio dominican university': ('Columbus', 'OH'),
    'alabama-huntsville': ('Huntsville', 'AL'),
    'university at buffalo': ('Buffalo', 'NY'),
    'grambling state': ('Grambling', 'LA'),
    'darton': ('Albany', 'GA'),
    'allan hancock': ('Santa Maria', 'CA'),
    'compton cc': ('Compton', 'CA'),
    'eastern utah': ('Price', 'UT'),
    'cc of rhode island': ('Warwick', 'RI'),
    'new haven': ('West Haven', 'CT'),
    'monroe cc': ('Rochester', 'NY'),
    'norwalk cc': ('Norwalk', 'CT'),
    'suny-cortland': ('Cortland', 'NY'),
    'treasure valley cc': ('Ontario', 'OR'),
    'los angeles cc': ('Los Angeles', 'CA'),
    'keystone college': ('La Plume', 'PA'),
    'maple woods cc': ('Kansas City', 'MO'),
    # NY/NE tail
    'suny-oneonta': ('Oneonta', 'NY'),
    'suny-oswego': ('Oswego', 'NY'),
    'suny-brockport': ('Brockport', 'NY'),
    'suny-geneseo': ('Geneseo', 'NY'),
    'suny-new paltz': ('New Paltz', 'NY'),
    'suny-plattsburgh': ('Plattsburgh', 'NY'),
    'suny-fredonia': ('Fredonia', 'NY'),
    'suny-potsdam': ('Potsdam', 'NY'),
    'suny-old westbury': ('Old Westbury', 'NY'),
    'suny-purchase': ('Purchase', 'NY'),
    'suny-maritime': ('Bronx', 'NY'),
    'suny-poly': ('Utica', 'NY'),
    'farmingdale state': ('Farmingdale', 'NY'),
    'st. joseph\'s (ny)': ('Patchogue', 'NY'),
    'molloy': ('Rockville Centre', 'NY'),
    'dowling': ('Oakdale', 'NY'),
    'adelphi': ('Garden City', 'NY'),
    'liu post': ('Brookville', 'NY'),
    'liu brooklyn': ('Brooklyn', 'NY'),
    'mercy (ny)': ('Dobbs Ferry', 'NY'),
    'concordia (ny)': ('Bronxville', 'NY'),
    'nyack': ('Nyack', 'NY'),
    'roberts wesleyan': ('Rochester', 'NY'),
    'houghton': ('Houghton', 'NY'),
    'nazareth': ('Rochester', 'NY'),
    'st. john fisher': ('Rochester', 'NY'),
    'ithaca': ('Ithaca', 'NY'),
    'rit': ('Rochester', 'NY'),
    'rensselaer': ('Troy', 'NY'),
    'union (ny)': ('Schenectady', 'NY'),
    'skidmore': ('Saratoga Springs', 'NY'),
    'hamilton (ny)': ('Clinton', 'NY'),
    'hartwick': ('Oneonta', 'NY'),
    'utica': ('Utica', 'NY'),
    'st. lawrence': ('Canton', 'NY'),
    'clarkson': ('Potsdam', 'NY'),
    'vassar': ('Poughkeepsie', 'NY'),
    'bard': ('Annandale-on-Hudson', 'NY'),
    'suffolk cc': ('Selden', 'NY'),
    'nassau cc': ('Garden City', 'NY'),
    'westchester cc': ('Valhalla', 'NY'),
    'rockland cc': ('Suffern', 'NY'),
    'dutchess cc': ('Poughkeepsie', 'NY'),
    'orange county cc (ny)': ('Middletown', 'NY'),
    'onondaga cc': ('Syracuse', 'NY'),
    'jamestown cc': ('Jamestown', 'NY'),
    'erie cc': ('Buffalo', 'NY'),
    'niagara county cc': ('Sanborn', 'NY'),
    'genesee cc': ('Batavia', 'NY'),
    'corning cc': ('Corning', 'NY'),
    'broome cc': ('Binghamton', 'NY'),
    'herkimer cc': ('Herkimer', 'NY'),
    'mohawk valley cc': ('Utica', 'NY'),
    'hudson valley cc': ('Troy', 'NY'),
    'schenectady county cc': ('Schenectady', 'NY'),
    'fulton-montgomery cc': ('Johnstown', 'NY'),
    'columbia-greene cc': ('Hudson', 'NY'),
    'ulster county cc': ('Stone Ridge', 'NY'),
    'rhode island college': ('Providence', 'RI'),
    'salve regina': ('Newport', 'RI'),
    'roger williams': ('Bristol', 'RI'),
    'johnson & wales': ('Providence', 'RI'),
    'western new england': ('Springfield', 'MA'),
    'american international': ('Springfield', 'MA'),
    'springfield (ma)': ('Springfield', 'MA'),
    'assumption': ('Worcester', 'MA'),
    'wpi': ('Worcester', 'MA'),
    'clark (ma)': ('Worcester', 'MA'),
    'nichols': ('Dudley', 'MA'),
    'bentley': ('Waltham', 'MA'),
    'brandeis': ('Waltham', 'MA'),
    'babson': ('Wellesley', 'MA'),
    'tufts': ('Medford', 'MA'),
    'suffolk (ma)': ('Boston', 'MA'),
    'emerson': ('Boston', 'MA'),
    'umass boston': ('Boston', 'MA'),
    'umass dartmouth': ('Dartmouth', 'MA'),
    'bridgewater state': ('Bridgewater', 'MA'),
    'salem state': ('Salem', 'MA'),
    'framingham state': ('Framingham', 'MA'),
    'worcester state': ('Worcester', 'MA'),
    'fitchburg state': ('Fitchburg', 'MA'),
    'westfield state': ('Westfield', 'MA'),
    'mass maritime': ('Buzzards Bay', 'MA'),
    'endicott': ('Beverly', 'MA'),
    'gordon (ma)': ('Wenham', 'MA'),
    'stonehill': ('Easton', 'MA'),
    'merrimack': ('North Andover', 'MA'),
    'amherst': ('Amherst', 'MA'),
    'williams': ('Williamstown', 'MA'),
    'wheaton (ma)': ('Norton', 'MA'),
    'curry': ('Milton', 'MA'),
    'quinsigamond cc': ('Worcester', 'MA'),
    'massasoit cc': ('Brockton', 'MA'),
    'cape cod cc': ('West Barnstable', 'MA'),
    'northern essex cc': ('Haverhill', 'MA'),
    'massbay cc': ('Wellesley Hills', 'MA'),
    'middlesex cc (ma)': ('Bedford', 'MA'),
    'holyoke cc': ('Holyoke', 'MA'),
    'springfield tech cc': ('Springfield', 'MA'),
    'gateway cc (ct)': ('New Haven', 'CT'),
    'gateway (ct)': ('New Haven', 'CT'),
    'manchester cc (ct)': ('Manchester', 'CT'),
    'middlesex cc (ct)': ('Middletown', 'CT'),
    'central connecticut state': ('New Britain', 'CT'),
    'eastern connecticut state': ('Willimantic', 'CT'),
    'western connecticut state': ('Danbury', 'CT'),
    'southern connecticut state': ('New Haven', 'CT'),
    'trinity (ct)': ('Hartford', 'CT'),
    'wesleyan (ct)': ('Middletown', 'CT'),
    'connecticut college': ('New London', 'CT'),
    'st. joseph (ct)': ('West Hartford', 'CT'),
    'albertus magnus': ('New Haven', 'CT'),
    'post (ct)': ('Waterbury', 'CT'),
    'gateway': ('New Haven', 'CT'),
    'keene state': ('Keene', 'NH'),
    'plymouth state': ('Plymouth', 'NH'),
    'rivier': ('Nashua', 'NH'),
    'saint anselm': ('Manchester', 'NH'),
    'new england college': ('Henniker', 'NH'),
    'colby-sawyer': ('New London', 'NH'),
    'nhti': ('Concord', 'NH'),
    'thomas (me)': ('Waterville', 'ME'),
    'husson': ('Bangor', 'ME'),
    'southern maine': ('Portland', 'ME'),
    'maine-augusta': ('Augusta', 'ME'),
    'maine-farmington': ('Farmington', 'ME'),
    'saint josephs (me)': ('Standish', 'ME'),
    'bowdoin': ('Brunswick', 'ME'),
    'bates': ('Lewiston', 'ME'),
    'colby (me)': ('Waterville', 'ME'),
    'castleton': ('Castleton', 'VT'),
    'norwich': ('Northfield', 'VT'),
    'saint michaels': ('Colchester', 'VT'),
    'champlain': ('Burlington', 'VT'),
    'middlebury': ('Middlebury', 'VT'),
    'colorado mesa': ('Grand Junction', 'CO'),
    'colorado state-pueblo': ('Pueblo', 'CO'),
    'colorado christian': ('Lakewood', 'CO'),
    'colorado school of mines': ('Golden', 'CO'),
    'fort lewis': ('Durango', 'CO'),
    'western colorado': ('Gunnison', 'CO'),
    'adams state': ('Alamosa', 'CO'),
    'colorado mines': ('Golden', 'CO'),
    'uccs': ('Colorado Springs', 'CO'),
    'northeastern junior college': ('Sterling', 'CO'),
    'otero junior college': ('La Junta', 'CO'),
    'lamar cc (co)': ('Lamar', 'CO'),
    'pueblo cc': ('Pueblo', 'CO'),
    'arapahoe cc': ('Littleton', 'CO'),
    'front range cc': ('Westminster', 'CO'),
    'western wyoming cc': ('Rock Springs', 'WY'),
    'casper college': ('Casper', 'WY'),
    'sheridan college': ('Sheridan', 'WY'),
    'laramie county cc': ('Cheyenne', 'WY'),
    'northwest college (wy)': ('Powell', 'WY'),
    'eastern wyoming': ('Torrington', 'WY'),
    'central wyoming': ('Riverton', 'WY'),
    'gillette college': ('Gillette', 'WY'),
    'salt lake cc (ut)': ('Salt Lake City', 'UT'),
    'snow college': ('Ephraim', 'UT'),
    'dixie state (ut)': ('St. George', 'UT'),
    'college of eastern utah': ('Price', 'UT'),
    'westminster (ut)': ('Salt Lake City', 'UT'),
    'utah valley university': ('Orem', 'UT'),
    'fresno pacific university': ('Fresno', 'CA'),

    # --- ninth tranche: full tail matched to exact register spellings ---
    'mercer county cc': ('West Windsor', 'NJ'),
    'briarcliffe college': ('Bethpage', 'NY'),
    'walla walla cc': ('Walla Walla', 'WA'),
    'southeastern university': ('Lakeland', 'FL'),
    'st. louis cc-meramec': ('St. Louis', 'MO'),
    'sw illinois college': ('Belleville', 'IL'),
    'surry cc': ('Dobson', 'NC'),
    'montclair state': ('Montclair', 'NJ'),
    'lackawanna college': ('Scranton', 'PA'),
    'lambuth': ('Jackson', 'TN'),
    'coastal ala south': ('Bay Minette', 'AL'),
    'lane college': ('Jackson', 'TN'),
    'long island-brooklyn': ('Brooklyn', 'NY'),
    'nebraska at omaha': ('Omaha', 'NE'),
    'mendocino college': ('Ukiah', 'CA'),
    'centenary la': ('Shreveport', 'LA'),
    'oklahoma christian': ('Edmond', 'OK'),
    'suny - albany': ('Albany', 'NY'),
    'wayne state university': ('Detroit', 'MI'),
    'delaware technical & cc': ('Dover', 'DE'),
    'arizona christian': ('Glendale', 'AZ'),
    'eastern new mexico': ('Portales', 'NM'),
    'indian hills cc-ottumwa': ('Ottumwa', 'IA'),
    'lake-sumter': ('Leesburg', 'FL'),
    'catonsville cc': ('Baltimore', 'MD'),
    'col of idaho': ('Caldwell', 'ID'),
    'spokane falls cc': ('Spokane', 'WA'),
    'skagit valley college': ('Mount Vernon', 'WA'),
    'augustana-sd': ('Sioux Falls', 'SD'),
    'texas wesleyan': ('Fort Worth', 'TX'),
    'st. thomas aquinas': ('Sparkill', 'NY'),
    'rowan': ('Glassboro', 'NJ'),
    'felician college': ('Lodi', 'NJ'),
    'lincoln memorial': ('Harrogate', 'TN'),
    'delaware state': ('Dover', 'DE'),
    'hope intl': ('Fullerton', 'CA'),
    'saint catharine': ('Springfield', 'KY'),
    'augustana-il': ('Rock Island', 'IL'),
    'truett-mcconnell': ('Cleveland', 'GA'),
    'william paterson': ('Wayne', 'NJ'),
    'southern indiana': ('Evansville', 'IN'),
    'south carolina-sumter': ('Sumter', 'SC'),
    'science and arts': ('Chickasha', 'OK'),
    'st. louis cc-forest park': ('St. Louis', 'MO'),
    'southwest mississippi cc': ('Summit', 'MS'),
    'ohio wesleyan': ('Delaware', 'OH'),
    'cerro coso cc': ('Ridgecrest', 'CA'),
    'coastal ala-brewton': ('Brewton', 'AL'),
    'mount vernon nazarene': ('Mount Vernon', 'OH'),
    'pasadena cc': ('Pasadena', 'CA'),
    'pierce college': ('Woodland Hills', 'CA'),
    'oakton': ('Des Plaines', 'IL'),
    'chemeketa cc': ('Salem', 'OR'),
    'corban': ('Salem', 'OR'),
    'indiana pa': ('Indiana', 'PA'),
    'elgin cc': ('Elgin', 'IL'),
    'florence-darlington tech': ('Florence', 'SC'),
    'dallas': ('Irving', 'TX'),
    'alcorn state': ('Lorman', 'MS'),
    'allegany college of maryland': ('Cumberland', 'MD'),
    'wenatchee valley cc': ('Wenatchee', 'WA'),
    'big bend cc': ('Moses Lake', 'WA'),
    'belhaven college': ('Jackson', 'MS'),
    'whittier': ('Whittier', 'CA'),
    'union commonwealth': ('Barbourville', 'KY'),
    'allegheny college': ('Meadville', 'PA'),
    'eastern ct state': ('Willimantic', 'CT'),
    'tacoma cc': ('Tacoma', 'WA'),
    'cumberland county college': ('Vineland', 'NJ'),
    'northwest shoals cc': ('Muscle Shoals', 'AL'),
    'mansfield': ('Mansfield', 'PA'),
    'ccbc dundalk': ('Baltimore', 'MD'),
    'cal state san marcos': ('San Marcos', 'CA'),
    'siu-edwardsville': ('Edwardsville', 'IL'),
    "saint joseph's indiana": ('Rensselaer', 'IN'),
    'linn-benton cc': ('Albany', 'OR'),
    'jones college': ('Ellisville', 'MS'),
    'kean': ('Union', 'NJ'),
    'saint xavier u. (ill.)': ('Chicago', 'IL'),
    'johns hopkins': ('Baltimore', 'MD'),
    'heartland cc': ('Normal', 'IL'),
    'illinois valley cc': ('Oglesby', 'IL'),
    'college of the siskiyous': ('Weed', 'CA'),
    'harford cc': ('Bel Air', 'MD'),
    'southern nazarene': ('Bethany', 'OK'),
    'emory': ('Atlanta', 'GA'),
    'connecticut-avery point': ('Groton', 'CT'),
    'ouachita baptist': ('Arkadelphia', 'AR'),
    'pacific lutheran': ('Tacoma', 'WA'),
    'ramapo': ('Mahwah', 'NJ'),
    'metro state': ('Denver', 'CO'),
    'wayne state-ne': ('Wayne', 'NE'),
    'mt. st. mary': ('Emmitsburg', 'MD'),
    'augusta state': ('Augusta', 'GA'),
    'webber intl': ('Babson Park', 'FL'),
    'millsaps': ('Jackson', 'MS'),
    'new mexico highlands': ('Las Vegas', 'NM'),
    'frederick cc': ('Frederick', 'MD'),
    'douglas college': ('New Westminster', 'BC'),
    'columbia greene cc': ('Hudson', 'NY'),
    'whitworth': ('Spokane', 'WA'),
    'west los angeles college': ('Culver City', 'CA'),
    'bacone college': ('Muskogee', 'OK'),
    'savannah college of art': ('Savannah', 'GA'),
    'northern ok tonkawa': ('Tonkawa', 'OK'),
    'missouri-st. louis': ('St. Louis', 'MO'),
    'missouri western state': ('St. Joseph', 'MO'),
    'north arkansas college': ('Harrison', 'AR'),
    'blue mountain cc': ('Pendleton', 'OR'),
    'alvernia': ('Reading', 'PA'),
    'arkansas-monticello': ('Monticello', 'AR'),
    'anderson sc': ('Anderson', 'SC'),
    'illinois wesleyan': ('Bloomington', 'IL'),
    'indiana tech': ('Fort Wayne', 'IN'),
    'coastal alabama-monroeville': ('Monroeville', 'AL'),
    'queensborough cc': ('Bayside', 'NY'),
    'olympic college': ('Bremerton', 'WA'),
    'messiah college': ('Mechanicsburg', 'PA'),
    'southern ct state': ('New Haven', 'CT'),
    "saint peter's": ('Jersey City', 'NJ'),
    'saint rose': ('Albany', 'NY'),
    'county college of morris': ('Randolph', 'NJ'),
    'glen oaks cc': ('Centreville', 'MI'),
    'hagerstown cc': ('Hagerstown', 'MD'),
    'hiwassee college': ('Madisonville', 'TN'),
    'haverford college': ('Haverford', 'PA'),
    'worcester state college': ('Worcester', 'MA'),
    'centralia college': ('Centralia', 'WA'),
    'mit': ('Cambridge', 'MA'),
    'mckendree university': ('Lebanon', 'IL'),
    'rio hondo cc': ('Whittier', 'CA'),
    'patrick & henry cc': ('Martinsville', 'VA'),
    'north idaho college': ('Coeur d\'Alene', 'ID'),
    'fisher college': ('Boston', 'MA'),
    "st. martin's": ('Lacey', 'WA'),
    'concordia ny': ('Bronxville', 'NY'),
    'westminster college': ('New Wilmington', 'PA'),
    'bentley college': ('Waltham', 'MA'),
    'trinity intl': ('Deerfield', 'IL'),
    'yakima valley college': ('Yakima', 'WA'),
    'detroit mercy': ('Detroit', 'MI'),
    'unc pembroke': ('Pembroke', 'NC'),
    'college of the redwoods': ('Eureka', 'CA'),
    'concordia mi': ('Ann Arbor', 'MI'),
    'stonehill college': ('Easton', 'MA'),
    'suffolk county cc-ammerman': ('Selden', 'NY'),
    'suny old westbury': ('Old Westbury', 'NY'),
    'college of lake county': ('Grayslake', 'IL'),
    'college of mount st. joseph': ('Cincinnati', 'OH'),
    'college of st scholastica': ('Duluth', 'MN'),
    'catawba valley': ('Hickory', 'NC'),
    'asa miami': ('Miami', 'FL'),
    'case western reserve': ('Cleveland', 'OH'),
    'california pa': ('California', 'PA'),
    'byu-idaho': ('Rexburg', 'ID'),
    'south carolina-beaufort': ('Bluffton', 'SC'),
    'se illinois': ('Harrisburg', 'IL'),
    'garrett college': ('McHenry', 'MD'),
    'indianapolis': ('Indianapolis', 'IN'),
    'st. john fisher college': ('Rochester', 'NY'),
    "st norbert's": ('De Pere', 'WI'),
    'tcnj': ('Ewing', 'NJ'),
    'st augustine college': ('Chicago', 'IL'),
    'concordia-st. paul': ('St. Paul', 'MN'),
    'endicott college': ('Beverly', 'MA'),
    'st. joseph\'s college': ('Standish', 'ME'),
    'brunswick cc': ('Supply', 'NC'),
    'hendrix': ('Conway', 'AR'),
    'henderson state': ('Arkadelphia', 'AR'),
    'hillsdale': ('Hillsdale', 'MI'),
    'rogers state': ('Claremore', 'OK'),
    'macmurray': ('Jacksonville', 'IL'),
    'lane cc or': ('Eugene', 'OR'),
    'keene state college': ('Keene', 'NH'),
    'northwestern-oh': ('Lima', 'OH'),
    'northern state': ('Aberdeen', 'SD'),
    'northern ok enid': ('Enid', 'OK'),
    'metropolitan cc-longview': ('Lees Summit', 'MO'),
    'northwestern oklahoma state': ('Alva', 'OK'),
    'mayville state university': ('Mayville', 'ND'),
    'park university': ('Parkville', 'MO'),
    'clackamas cc': ('Oregon City', 'OR'),
    'purdue fort wayne': ('Fort Wayne', 'IN'),
    'clark college': ('Vancouver', 'WA'),
    'pitt bradford': ('Bradford', 'PA'),
    'cc of san francisco': ('San Francisco', 'CA'),
    'montgomery college': ('Rockville', 'MD'),
    'monmouth il': ('Monmouth', 'IL'),
    'midamerica nazarene': ('Olathe', 'KS'),
    'cecil college': ('North East', 'MD'),
    'central methodist university': ('Fayette', 'MO'),
    'msu billings': ('Billings', 'MT'),
    'wilmington college of ohio': ('Wilmington', 'OH'),
    'new jersey tech': ('Newark', 'NJ'),
    'wilkes cc': ('Wilkesboro', 'NC'),
    'wv wesleyan': ('Buckhannon', 'WV'),
    'babson college': ('Wellesley', 'MA'),
    'anne arundel cc': ('Arnold', 'MD'),
    'washburn university': ('Topeka', 'KS'),
    'washington u. in st. louis': ('St. Louis', 'MO'),
    'washington and lee': ('Lexington', 'VA'),
    'washington & jefferson': ('Washington', 'PA'),
    'waldorf': ('Forest City', 'IA'),
    'western ct state': ('Danbury', 'CT'),
    'arkansas baptist college': ('Little Rock', 'AR'),
    'american intl college': ('Springfield', 'MA'),
    'alma': ('Alma', 'MI'),
    'texas a&m international': ('Laredo', 'TX'),
    'tennessee temple': ('Chattanooga', 'TN'),
    'adrian': ('Adrian', 'MI'),
    'wilmington university': ('New Castle', 'DE'),
    'williams': ('Williamstown', 'MA'),
    'william woods university': ('Fulton', 'MO'),
    'william jessup': ('Rocklin', 'CA'),
    'wesleyan university': ('Middletown', 'CT'),
    'neumann college': ('Aston', 'PA'),
    'central state': ('Wilberforce', 'OH'),
    'central piedmont': ('Charlotte', 'NC'),
    'cedar valley college': ('Lancaster', 'TX'),
    'molloy college': ('Rockville Centre', 'NY'),
    'minnesota, crookston': ('Crookston', 'MN'),
    'midway college': ('Midway', 'KY'),
    'middlesex county college': ('Edison', 'NJ'),
    'miami university hamilton': ('Hamilton', 'OH'),
    'north central mn': ('Minneapolis', 'MN'),
    'njcu': ('Jersey City', 'NJ'),
    'ccbc catonsville': ('Baltimore', 'MD'),
    'cc of allegheny county': ('Pittsburgh', 'PA'),
    'oglethorpe': ('Atlanta', 'GA'),
    'northwood university': ('Midland', 'MI'),
    'northeastern illinois': ('Chicago', 'IL'),
    'lenoir cc': ('Kinston', 'NC'),
    'lehman college': ('Bronx', 'NY'),
    'mcdaniel college': ('Westminster', 'MD'),
    'mary hardin-baylor': ('Belton', 'TX'),
    'northampton cc': ('Bethlehem', 'PA'),
    'pitt-johnstown': ('Johnstown', 'PA'),
    'pacific university': ('Forest Grove', 'OR'),
    'ripon college': ('Ripon', 'WI'),
    'rio grande': ('Rio Grande', 'OH'),
    'reinhardt university': ('Waleska', 'GA'),
    'raritan valley cc': ('Branchburg', 'NJ'),
    'puget sound': ('Tacoma', 'WA'),
    'prairie state college': ('Chicago Heights', 'IL'),
    'san francisco state': ('San Francisco', 'CA'),
    'salem state': ('Salem', 'MA'),
    'coahoma cc': ('Clarksdale', 'MS'),
    'claflin university': ('Orangeburg', 'SC'),
    'iu southeast': ('New Albany', 'IN'),
    'lsu-alexandria': ('Alexandria', 'LA'),
    'louisiana christian': ('Pineville', 'LA'),
    'los angeles valley': ('Valley Glen', 'CA'),
    'lock haven': ('Lock Haven', 'PA'),
    'lincoln-pa': ('Lincoln University', 'PA'),
    'king college (tenn.)': ('Bristol', 'TN'),
    'kankakee cc': ('Kankakee', 'IL'),
    'juniata college': ('Huntingdon', 'PA'),
    'john wood cc': ('Quincy', 'IL'),
    'coast guard': ('New London', 'CT'),
    "saint michael's vt": ('Colchester', 'VT'),
    'rutgers-newark': ('Newark', 'NJ'),
    'rutgers-camden': ('Camden', 'NJ'),
    'southeastern cc nc': ('Whiteville', 'NC'),
    'shoreline cc': ('Shoreline', 'WA'),
    'scranton': ('Scranton', 'PA'),
    'asbury college': ('Wilmore', 'KY'),
    'carroll mt': ('Helena', 'MT'),
    'calumet col of st. joseph': ('Whiting', 'IN'),
    'c.w. post campus/long island': ('Brookville', 'NY'),
    'bryan college tn': ('Dayton', 'TN'),
    'georgia southwestern state': ('Americus', 'GA'),
    'frostburg state': ('Frostburg', 'MD'),
    'itasca cc': ('Grand Rapids', 'MN'),
    'iowa wesleyan': ('Mount Pleasant', 'IA'),
    'indiana university-kokomo': ('Kokomo', 'IN'),
    'illinois at springfield': ('Springfield', 'IL'),
    'huston-tillotson': ('Austin', 'TX'),
    'houston-victoria': ('Victoria', 'TX'),
    'houghton college': ('Houghton', 'NY'),
    'college of wooster': ('Wooster', 'OH'),
    'eastern oregon': ('La Grande', 'OR'),
    'hamilton college': ('Clinton', 'NY'),
    'grove city college': ('Grove City', 'PA'),
    'bronx cc': ('Bronx', 'NY'),
    'brescia university': ('Owensboro', 'KY'),
    'st. clair county cc': ('Port Huron', 'MI'),
    'spokane cc': ('Spokane', 'WA'),
    'spalding': ('Louisville', 'KY'),
    'southern wesleyan university': ('Central', 'SC'),
    'franklin & marshall college': ('Lancaster', 'PA'),
    'folsom lake': ('Folsom', 'CA'),
    'finger lakes cc': ('Canandaigua', 'NY'),
    'essex cc': ('Baltimore', 'MD'),
    'cornerstone': ('Grand Rapids', 'MI'),
    'sw oregon cc': ('Coos Bay', 'OR'),
    'susquehanna': ('Selinsgrove', 'PA'),
    'suny-farmingdale': ('Farmingdale', 'NY'),
    'sul ross state': ('Alpine', 'TX'),
    'stillman college': ('Tuscaloosa', 'AL'),
    'stevens tech': ('Hoboken', 'NJ'),
    'uw river falls': ('River Falls', 'WI'),
    'usc-salkehatchie': ('Allendale', 'SC'),
    'ursinus college': ('Collegeville', 'PA'),
    'upper iowa': ('Fayette', 'IA'),
    'alfred university': ('Alfred', 'NY'),
    'college of staten island': ('Staten Island', 'NY'),
    'dupage': ('Glen Ellyn', 'IL'),
    'dominican university': ('River Forest', 'IL'),
    'desales': ('Center Valley', 'PA'),
    'dawson cc': ('Glendive', 'MT'),
    'dana college': ('Blair', 'NE'),
    'dakota wesleyan university': ('Mitchell', 'SD'),
    'thomas university': ('Thomasville', 'GA'),
    'virginia peninsula': ('Hampton', 'VA'),
    'victory university': ('Memphis', 'TN'),
    'bevill state cc-fayette': ('Fayette', 'AL'),
    'bethel ks': ('North Newton', 'KS'),
    'benedictine springfield': ('Springfield', 'IL'),
    'bates college': ('Lewiston', 'ME'),
    'baker university': ('Baldwin City', 'KS'),
    'west georgia tech': ('Waco', 'GA'),
    'west liberty university': ('West Liberty', 'WV'),
    'adams state': ('Alamosa', 'CO'),
    'wor-wic': ('Salisbury', 'MD'),
    'alma college': ('Alma', 'MI'),
    'texas a&m international university': ('Laredo', 'TX'),
    'new york': ('New York', 'NY'),
    'brandeis': ('Waltham', 'MA'),
    'nassau cc': ('Garden City', 'NY'),
    'chicago': ('Chicago', 'IL'),
    'salem international': ('Salem', 'WV'),
    'coppin state': ('Baltimore', 'MD'),
    'east central mo': ('Union', 'MO'),
    'ulster county cc': ('Stone Ridge', 'NY'),
    'st. clair (mi)': ('Port Huron', 'MI'),
    'lsu alexandria': ('Alexandria', 'LA'),
    'rpi': ('Troy', 'NY'),
    'tufts': ('Medford', 'MA'),
    'concordia mi': ('Ann Arbor', 'MI'),
    'california tech': ('Pasadena', 'CA'),
    'illinois wesleyan university': ('Bloomington', 'IL'),
    'iowa wesleyan university': ('Mount Pleasant', 'IA'),
    'south carolina beaufort': ('Bluffton', 'SC'),
    'herkimer': ('Herkimer', 'NY'),
    'ithaca': ('Ithaca', 'NY'),
    'dowling': ('Oakdale', 'NY'),
    'amherst': ('Amherst', 'MA'),
    'rockland cc': ('Suffern', 'NY'),
    'southern maine': ('Portland', 'ME'),
    'merrimack college': ('North Andover', 'MA'),
    'adelphi': ('Garden City', 'NY'),
    'monroe cc': ('Rochester', 'NY'),
    'new haven': ('West Haven', 'CT'),
    'los angeles cc': ('Los Angeles', 'CA'),
    'keystone college': ('La Plume', 'PA'),
    'maple woods cc': ('Kansas City', 'MO'),
    'suny-cortland': ('Cortland', 'NY'),
    'norwalk cc': ('Norwalk', 'CT'),
    'cc of rhode island': ('Warwick', 'RI'),
    'treasure valley cc': ('Ontario', 'OR'),
    'regis': ('Denver', 'CO'),
    'darton': ('Albany', 'GA'),
    'compton cc': ('Compton', 'CA'),
    'allan hancock': ('Santa Maria', 'CA'),
    'eastern utah': ('Price', 'UT'),
    'new york tech': ('Old Westbury', 'NY'),
    'houston christian': ('Houston', 'TX'),
    'csu-pueblo': ('Pueblo', 'CO'),
    'lurleen b. wallace': ('Andalusia', 'AL'),
    'ohio dominican university': ('Columbus', 'OH'),
    'alabama-huntsville': ('Huntsville', 'AL'),
    'university at buffalo': ('Buffalo', 'NY'),
    'grambling state': ('Grambling', 'LA'),

    # --- final cleanup: last real schools (skip junk 'fl', 'advanced software analysis') ---
    'lindenwood university': ('St. Charles', 'MO'),
    'point park': ('Pittsburgh', 'PA'),
    'morton': ('Cicero', 'IL'),
    'mississippi christian': ('Blue Mountain', 'MS'),
    'st. katherine': ('San Marcos', 'CA'),
    'lexington college': ('Chicago', 'IL'),
    'claremont college': ('Claremont', 'CA'),
    'colorado springs': ('Colorado Springs', 'CO'),
    'chesapeake': ('Wye Mills', 'MD'),
    'massachusetts-boston': ('Boston', 'MA'),
    'mcla': ('North Adams', 'MA'),
    'penn state berks-lehigh val': ('Reading', 'PA'),
    'patten college': ('Oakland', 'CA'),
    'ridgewater': ('Willmar', 'MN'),
    'pennwest clarion': ('Clarion', 'PA'),
    'rochester tech': ('Rochester', 'NY'),
    'central baptist': ('Conway', 'AR'),
    'lindenwood': ('St. Charles', 'MO'),
    'shawnee state university': ('Portsmouth', 'OH'),
    'rust': ('Holly Springs', 'MS'),           # Rust College
    'mary': ('Bismarck', 'ND'),                # University of Mary
    'westmar': ('Le Mars', 'IA'),              # defunct, best-effort
    'kingsburg (kingsburg,ca)': ('Kingsburg', 'CA'),

    # --- verified fixes from manual player lookup ---
    # 'trinity college' players are all New England NCAA 3 -> Trinity (Hartford CT),
    # NOT Trinity University San Antonio. Exact keys beat the alias collapse.
    'trinity college': ('Hartford', 'CT'),
    # 'union u' players are Tennessee NAIA -> Union University (Jackson TN),
    # NOT Union College Barbourville KY.
    'union u': ('Jackson', 'TN'),
    'union university': ('Jackson', 'TN'),
}


def normalize(name):
    """Match the register's normalization exactly."""
    return str(name).strip().lower()


# Per-PLAYER location overrides (keyed on register PlayerID) for cases where one
# school name maps to several real campuses. Checked BEFORE the school crosswalk.
# 'concordia university' resolves to 4 different Concordias by birth-state/division
# (verified from player birth places + division):
PLAYER_OVERRIDE = {
    # Concordia Chicago (River Forest, IL) -- Illinois NCAA 3
    37779:  ('River Forest', 'IL'),   # Jim Paduch
    148595: ('River Forest', 'IL'),   # Jack Walker
    165643: ('River Forest', 'IL'),   # Nick Skala
    # Concordia Texas (Austin, TX) -- Texas NCAA 3
    148300: ('Austin', 'TX'),         # Michael Johnson
    180732: ('Austin', 'TX'),         # Ryan Ullmann
    175808: ('Austin', 'TX'),         # Corey Holmes
    203825: ('Austin', 'TX'),         # Lane Hobbs
    # Concordia Portland (Portland, OR) -- Pacific NW NAIA
    5602:   ('Portland', 'OR'),       # Jesse Harrington
    46059:  ('Portland', 'OR'),       # Michael Devaney
    # Concordia Irvine (CA) -- California NAIA
    187942: ('Irvine', 'CA'),         # Blake Drake
    165357: ('Irvine', 'CA'),         # Nate Esposito
}


def lookup_player(player_id):
    """Per-player override by register PlayerID; None if no override."""
    try:
        return PLAYER_OVERRIDE.get(int(player_id))
    except (ValueError, TypeError):
        return None


# common noise tokens/suffixes to strip for ALIAS matching (a looser second pass)
import re as _re

_NOISE = [
    ' community college', ' junior college', ' college', ' university',
    ' cc', ' jc', ' u.', ' st.', ' state college',
]
_ABBREV = {
    ' st ': ' state ', ' st.': ' state', ' univ': ' university',
    ' u ': ' university ', 'so ': 'southern ', 'se ': 'southeast ',
    'sw ': 'southwest ', 'ne ': 'northeast ', 'nw ': 'northwest ',
    ' cc': '', ' jc': '',
}

# state-name expansions so 'uw whitewater' == 'wisconsin whitewater', etc.
_STATE_ALIAS = {
    'uw ': 'wisconsin ', 'uc ': 'california ', 'ut ': 'texas ',
    'nc ': 'north carolina ', 'sc ': 'south carolina ',
    'massachusetts lowell': 'umass lowell', 'mass lowell': 'umass lowell',
    'penn state': 'pennsylvania state', 'ala ': 'alabama ',
    'miss ': 'mississippi ', 'tenn ': 'tennessee ', 'ga ': 'georgia ',
    'fla ': 'florida ', 'cal ': 'california ', 'ark ': 'arkansas ',
    'okla ': 'oklahoma ', 'wash ': 'washington ', 'ill ': 'illinois ',
    'ind ': 'indiana ', 'ky ': 'kentucky ', 'la ': 'louisiana ',
    'tex ': 'texas ', 'ariz ': 'arizona ', 'colo ': 'colorado ',
    'conn ': 'connecticut ', 'mich ': 'michigan ', 'minn ': 'minnesota ',
    'mo ': 'missouri ', 'neb ': 'nebraska ', 'nev ': 'nevada ',
    'ore ': 'oregon ', 'va ': 'virginia ', 'wis ': 'wisconsin ',
}


def alias_key(name):
    """A looser normalized key: strip noise tokens, punctuation, state suffixes
    so 'Chaffey', 'chaffey college', 'chaffey cc' all collapse to 'chaffey'."""
    s = ' ' + str(name).strip().lower() + ' '
    s = s.replace('&', 'and').replace('-', ' ').replace('.', '').replace(',', '')
    s = s.replace("'", '')
    # drop trailing state-in-parens like '(ca)' '(tx)'
    s = _re.sub(r'\(([a-z]{2})\)', '', s)
    # state prefix aliases (uw -> wisconsin, etc.)
    for a, b in _STATE_ALIAS.items():
        if s.strip().startswith(a.strip() + ' ') or (' ' + a) in s:
            s = s.replace(' ' + a, ' ' + b)
    for a, b in _ABBREV.items():
        s = s.replace(a, b)
    for tok in [' community college', ' junior college', ' college',
                ' university', ' cc ', ' jc ', ' area ']:
        s = s.replace(tok, ' ')
    s = _re.sub(r'\s+', ' ', s).strip()
    return s


# build an alias index from the main crosswalk (once, at import)
_ALIAS_INDEX = {}
for _k, _v in list(CROSSWALK.items()):
    _ALIAS_INDEX.setdefault(alias_key(_k), _v)


def lookup(name):
    """Exact match first; then a looser alias match (noise-stripped)."""
    exact = CROSSWALK.get(normalize(name))
    if exact:
        return exact
    return _ALIAS_INDEX.get(alias_key(name))
